/* ---------------- currículo MSA ---------------- */
const FASES = [
 {f:1,p:1,nome:"Música, som, notas, pentagrama e claves",tops:[["Introdução","Origem e finalidade da orquestra na CCB"],["1.1–1.3","Música. Som. Elementos e propriedades"],["1.4","Notas musicais"],["1.5","Pentagrama"],["1.6","Claves"]]},
 {f:2,p:1,nome:"Figuras, compasso e fórmula em 4",tops:[["2.1","Figuras musicais"],["2.2–2.3","Compasso. Barras de compasso"],["2.4","Fórmula de compasso em 4"],["2.5–2.6","Ritmo. Pulsação. Exercícios rítmicos"]]},
 {f:3,p:1,nome:"Endecagrama, leitura e condução",tops:[["3.1","Endecagrama"],["3.2","Leitura rítmica, métrica e solfejo"],["3.3–3.4","Movimentos de condução e de solfejo em 4"],["3.5","Metrônomo"]]},
 {f:4,p:2,nome:"Ligadura, ponto, intervalo, fórmulas em 3 e 2",tops:[["4.1","Ligadura"],["4.2","Ponto de aumento"],["4.3","Intervalo"],["4.4–4.5","Fórmula e solfejo em 3"],["4.6–4.7","Fórmula e solfejo em 2"]]},
 {f:5,p:2,nome:"Tercinas, fermata e fórmula em 6",tops:[["5.1","Tercinas"],["5.2","Fermata"],["5.3–5.5","Fórmula e solfejo em 6"]]},
 {f:6,p:3,nome:"Tom, semitom, acidentes e escalas",tops:[["6.1","Tom e semitom"],["6.2","Acidentes — sustenido e bemol"],["6.3–6.4","Escalas. Escalas diatônicas"],["6.5–6.7","Escalas maiores com sustenidos e bemóis"]]},
 {f:7,p:3,nome:"Armadura de clave e fórmulas em 9 e 12",tops:[["7.1","Armadura de clave"],["7.2–7.4","Fórmula e solfejo em 9"],["7.5–7.7","Fórmula e solfejo em 12"]]},
 {f:8,p:3,nome:"Tonalidade e acidentes ocorrentes",tops:[["8.1","Tonalidade"],["8.2","Acidentes ocorrentes e de precaução"]]},
 {f:9,p:3,nome:"Barras de repetição",tops:[["9.1","Barra de compasso — repetição"]]},
 {f:10,p:4,nome:"Dinâmica",tops:[["10.1","Dinâmica"]]},
 {f:11,p:4,nome:"Acento métrico e tipos de compasso",tops:[["11.1","Acento métrico"],["11.2–11.3","Compasso simples e composto"],["11.4","Compassos alternados"]]},
 {f:12,p:4,nome:"Síncopa e contratempo",tops:[["12.1–12.2","Síncopa. Contratempo"]]},
 {f:13,p:4,nome:"Ritmos iniciais",tops:[["13.1","Tético, anacrúsico e acéfalo"]]},
 {f:14,p:4,nome:"Notas pontuadas",tops:[["14.1","Notas pontuadas e subdivisão"]]},
 {f:15,p:4,nome:"Andamento",tops:[["15.1","Andamento"],["15.2","Poco rallentando"],["15.3","Modificação indevida de andamento"]]},
 {f:16,p:4,nome:"Frases e interpretação",tops:[["16.1","Frases e semifrases"],["16.2","Interpretação musical"],["16.3","Indicações interpretativas"]]}
];
const TIPOS = {
  ver:      {rot:"Identificar", canal:"papel",   desc:"nomear o que está escrito"},
  entender: {rot:"Explicar",    canal:"papel",   desc:"por que é assim"},
  erro:     {rot:"Achar o erro",canal:"papel",   desc:"corrigir o que está errado"},
  comparar: {rot:"Comparar",    canal:"papel",   desc:"dois hinos lado a lado"},
  criar:    {rot:"Produzir",    canal:"papel",   desc:"escrever ou marcar algo novo"},
  tocar:    {rot:"Tocar",       canal:"pratica", desc:"com o instrumento na mão"},
  ouvir:    {rot:"Ouvir",       canal:"pratica", desc:"o instrutor toca, o aluno responde"},
  decidir:  {rot:"Decidir",     canal:"pratica", desc:"situação real de ensaio"}
};

/* Plano de aulas do MSA, por período — Manual de aplicação das Aulas do MSA, v2.7.
   Cada item: [nº da aula, tópicos do MSA, assunto]. */
const AULAS = {
 1:[[1,"Introdução","Origem e finalidade da orquestra na CCB"],
    [2,"1.1, 1.2, 1.3","Música. Som. Elementos. Propriedades"],
    [3,"1.4","Notas musicais"],
    [4,"1.5, 1.6","Pentagrama. Claves"],
    [5,"2.1","Figuras musicais"],
    [6,"2.2, 2.3","Compasso. Barras de compasso"],
    [7,"2.4","Fórmula de compasso em 4"],
    [8,"2.5, 2.6","Ritmo. Pulsação. Formas de realização de exercícios rítmicos"],
    [9,"2.6","Formas de realização de exercícios rítmicos (continuação)"],
    [10,"3.1","Endecagrama"],
    [11,"3.2","Leitura rítmica. Leitura métrica e solfejo"],
    [12,"3.3, 3.4","Movimentos de condução. Movimentos de solfejo em 4"],
    [13,"3.4","Movimentos de solfejo em 4 (continuação)"],
    [14,"3.5","Metrônomo"],
    [15,"1.1 a 3.5","Conclusão e avaliação do período"]],
 2:[[1,"4.1, 4.2, 4.3","Ligadura. Ponto de aumento. Intervalo"],
    [2,"4.4, 4.5","Fórmula de compasso em 3. Movimento de solfejo em 3"],
    [3,"4.5","Movimento de solfejo em 3. Exercício de leitura rítmica"],
    [4,"","Movimento de solfejo em 3. Exercício de leitura métrica"],
    [5,"","Movimento de solfejo em 3. Exercício de leitura métrica (continuação)"],
    [6,"4.6, 4.7","Fórmula de compasso em 2. Movimento de solfejo em 2"],
    [7,"4.7","Movimento de solfejo em 2. Exercícios de leitura rítmica"],
    [8,"","Movimento de solfejo em 2. Exercícios de leitura métrica"],
    [9,"","Movimento de solfejo em 2. Exercícios de leitura métrica (continuação)"],
    [10,"5.1","Tercinas. Exercícios de leitura rítmica e solfejo. Hinos"],
    [11,"","Tercinas. Exercícios de leitura rítmica e solfejo. Hinos (continuação)"],
    [12,"5.2","Fermata. Exercícios"],
    [13,"5.3, 5.4","Fórmula de compasso em 6. Movimento de solfejo em 6"],
    [14,"5.5","Movimento alternativo de solfejo em 6. Exercícios"],
    [15,"4.1 a 5.5","Conclusão dos exercícios individuais por candidato"]],
 3:[[1,"6.1, 6.2","Tom e semitom. Acidentes — sustenido e bemol"],
    [2,"6.3, 6.4","Escalas. Escalas diatônicas"],
    [3,"6.5, 6.6","Escalas maiores. Escalas maiores com sustenidos"],
    [4,"6.7","Escalas maiores com bemóis. Exercícios"],
    [5,"7.1","Armadura de clave"],
    [6,"7.2, 7.3","Fórmula de compasso em 9. Movimento de solfejo em 9"],
    [7,"7.4","Movimento alternativo para solfejo em 9. Exercícios"],
    [8,"7.5, 7.6","Fórmula de compasso em 12. Movimento de solfejo em 12"],
    [9,"7.7","Movimento alternativo para solfejo em 12. Exercícios"],
    [10,"","Movimento alternativo para solfejo em 12 (continuação)"],
    [11,"","Movimento alternativo para solfejo em 12 (continuação)"],
    [12,"8.1","Tonalidade. Exercícios"],
    [13,"8.2","Acidentes ocorrentes e de precaução. Exercícios"],
    [14,"9.1","Barra de compasso — repetição"],
    [15,"6.1 a 9.1","Conclusão dos exercícios individuais por candidato"]],
 4:[[1,"10.1","Dinâmica. Exercícios"],
    [2,"11.1, 11.2, 11.3","Acento métrico. Compasso simples. Compasso composto"],
    [3,"11.4","Compassos alternados. Exercícios"],
    [4,"12.1, 12.2","Síncopa. Contratempo. Exercícios"],
    [5,"","Síncopa. Contratempo. Exercícios (continuação)"],
    [6,"13.1","Ritmos iniciais. Exercícios"],
    [7,"","Ritmos iniciais. Exercícios (continuação)"],
    [8,"14.1","Notas pontuadas. Diferenças na subdivisão"],
    [9,"","Notas pontuadas. Diferenças na subdivisão (continuação)"],
    [10,"","Notas pontuadas. Diferenças na subdivisão (continuação)"],
    [11,"15.1, 15.2","Andamento. Modificação de andamento — poco rallentando"],
    [12,"15.3","Modificação indevida de andamento"],
    [13,"16.1, 16.2","Frases e semifrases. Interpretação musical"],
    [14,"16.3","Indicações interpretativas. Exercícios"],
    [15,"10.1 a 16.3","Indicações interpretativas (continuação). Conclusão do curso"]]
};
