/* Tabela dos hinos, extraída do hinário pelo ferramentas/extrair-hinario.py.

   Do cabeçalho:
   n    número do hino
   tom  tonalidade impressa
   marc movimento de marcação impresso ("em 2", "em 6"...), quando aparece
   met  marcação de metrônomo
   ind  indicação interpretativa

   Da partitura (lida em 24/09/2026 — ver o script):
   fc   fórmulas de compasso, na ordem em que aparecem. Mais de uma quando o
        hino muda de compasso. "C" é o C de 4/4; "C cortado", o de 2/2.
        Conferido contra todas as listas do GEM que dependem de compasso.
   ri   ritmo inicial: tético, anacrúsico ou acéfalo. É o dado menos certo da
        tabela — sai do selo de regência do Maestro e da largura do primeiro
        compasso, e os casos duvidosos foram olhados um a um. Conferir no
        hinário antes de usar em avaliação.
   s    sinais presentes: pontuada (nota pontuada), fermata, tercina, ritornelo.

   Nenhum desses campos reproduz a partitura: é informação sobre o hino, da
   mesma natureza da tonalidade.

   São os 480 hinos. O 434 não estava no PDF de onde o resto saiu — o 433 e o
   435 estão lá em páginas seguidas — e foi lido à mão da página que o Anderson
   digitalizou: Dó maior (clave de Sol sem acidente na armadura), compasso 4/4,
   metrônomo 66-84, sem indicação interpretativa. A marcação fica vazia porque
   a página que ele mandou é a do hinário com letra, que não traz esse campo.
   Do 434 não há ritmo inicial nem sinais: a página não foi lida pelo script.

   O 230 não traz fórmula de compasso impressa no começo, e fica sem "fc".

   Os hinos avulsos do fim do hinário não entram: eles recomeçam a numeração
   do 1 e colidiriam com os primeiros hinos.

   As marcações dos hinos 457 e 459 são anotação do Anderson na linha do
   título, e não impressão do hinário. Ficam porque ele as conferiu. */
const HINOS = [
{n:1,tom:"Mi♭",met:"56-66",fc:["4/4"],ri:"tético",s:["pontuada","fermata"]},
{n:2,tom:"Mi♭",met:"60-80",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:3,tom:"Sol",fc:["4/4"],ri:"tético",s:["pontuada","fermata"]},
{n:4,tom:"Lá♭",marc:"em 2",met:"112-138",fc:["6/4"],ri:"tético",s:["pontuada","fermata"]},
{n:5,tom:"Lá♭",marc:"em 2",met:"112-144",fc:["6/8"],ri:"tético",s:["pontuada"]},
{n:6,tom:"Dó",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata","ritornelo"]},
{n:7,tom:"Mi♭",marc:"em 6",met:"80-100",fc:["6/4"],ri:"anacrúsico",s:["pontuada"]},
{n:8,tom:"Si♭",marc:"em 2",fc:["6/8"],ri:"tético",s:["pontuada"]},
{n:9,tom:"Sol",met:"63-72",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:10,tom:"Si♭",met:"69-84",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:11,tom:"Si♭",met:"72-84",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:12,tom:"Mi♭",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata","tercina"]},
{n:13,tom:"Lá♭",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:14,tom:"Fá",met:"112-144",fc:["6/8"],ri:"tético",s:["pontuada"]},
{n:15,tom:"Si♭",marc:"em 4",fc:["12/8"],ri:"tético",s:["pontuada"]},
{n:16,tom:"Sol",marc:"em 6",met:"100-120",fc:["6/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:17,tom:"Sol",met:"60-76",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:18,tom:"Sol",met:"76-92",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:19,tom:"Lá♭",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:20,tom:"Fá",met:"72-84",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:21,tom:"Mi♭",marc:"em 6",met:"116-138",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata","ritornelo"]},
{n:22,tom:"Lá",marc:"em 6",met:"104-132",fc:["6/8"],ri:"tético",s:["pontuada"]},
{n:23,tom:"Sol",marc:"em 6",met:"96-120",fc:["6/4"],ri:"tético",s:["pontuada","fermata"]},
{n:24,tom:"Sol",marc:"em 6",fc:["6/4"],ri:"anacrúsico",s:["pontuada"]},
{n:25,tom:"Sol",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:26,tom:"Lá♭",met:"69-88",fc:["4/4"],ri:"tético",s:["pontuada","fermata"]},
{n:27,tom:"Mi♭",marc:"em 2",met:"116-144",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:28,tom:"Dó",met:"69-80",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:29,tom:"Lá♭",met:"66-84",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:30,tom:"Fá",marc:"em 6",fc:["6/8"],ri:"tético",s:["pontuada","fermata"]},
{n:31,tom:"Ré",met:"60-76",fc:["2/2"],ri:"tético",s:["pontuada","fermata"]},
{n:32,tom:"Lá♭",marc:"em 4",met:"52-72",fc:["2/4"],ri:"tético",s:["pontuada","fermata"]},
{n:33,tom:"Dó",marc:"em 4",fc:["6/8"],ri:"tético",s:["pontuada","fermata"]},
{n:34,tom:"Mi♭",met:"50-66",fc:["3/4"],ri:"anacrúsico",s:["pontuada"]},
{n:35,tom:"Mi♭",met:"108-120",fc:["6/8"],ri:"anacrúsico",s:["pontuada"]},
{n:36,tom:"Sol",met:"84-100",fc:["6/4"],ri:"anacrúsico",s:["pontuada"]},
{n:37,tom:"Ré",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:38,tom:"Mi♭",fc:["4/4"],ri:"tético",s:["pontuada","fermata"]},
{n:39,tom:"Fá",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:40,tom:"Lá♭",met:"72-88",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:41,tom:"Lá",marc:"em 3",met:"120-144",fc:["9/8"],ri:"anacrúsico",s:["pontuada","fermata","ritornelo"]},
{n:42,tom:"Fá",marc:"em 4",met:"50-60",fc:["12/8"],ri:"anacrúsico",s:["pontuada","fermata","ritornelo"]},
{n:43,tom:"Mi♭",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:44,tom:"Fá",marc:"em 3",fc:["9/8"],ri:"anacrúsico",s:["pontuada"]},
{n:45,tom:"Dó",marc:"em 3",met:"96-120",fc:["9/4"],ri:"tético",s:["pontuada","fermata"]},
{n:46,tom:"Lá♭",marc:"em 2",fc:["6/8"],ri:"tético",s:["pontuada","fermata"]},
{n:47,tom:"Fá",marc:"em 2",met:"120-152",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata","ritornelo"]},
{n:48,tom:"Mi♭",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:49,tom:"Fá",marc:"em 6",fc:["6/4"],ri:"tético",s:["pontuada","fermata"]},
{n:50,tom:"Dó",marc:"em 2",fc:["6/8"],ri:"tético",s:["pontuada","fermata","ritornelo"]},
{n:51,tom:"Si♭",marc:"em 4",fc:["C"],ri:"tético"},
{n:52,tom:"Dó",fc:["6/8"],ri:"tético",s:["pontuada","fermata"]},
{n:53,tom:"Mi♭",marc:"em 4",met:"72-92",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:54,tom:"Fá",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:55,tom:"Dó",marc:"em 2",fc:["6/8"],ri:"tético",s:["pontuada","fermata"]},
{n:56,tom:"Mi♭",met:"70-84",fc:["C"],ri:"tético",s:["pontuada","fermata","ritornelo"]},
{n:57,tom:"Ré♭",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:58,tom:"Ré",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:59,tom:"Fá",fc:["3/4"],ri:"anacrúsico",s:["pontuada"]},
{n:60,tom:"Fá",marc:"em 2",met:"116-132",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:61,tom:"Mi♭",marc:"em 3",fc:["9/8"],ri:"anacrúsico",s:["pontuada","fermata","ritornelo"]},
{n:62,tom:"Lá♭",met:"63-80",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:63,tom:"Si♭",marc:"em 3",met:"46-56",fc:["9/8"],ri:"anacrúsico",s:["pontuada","fermata","ritornelo"]},
{n:64,tom:"Fá",met:"69-88",fc:["3/4"],ri:"tético",s:["pontuada"]},
{n:65,tom:"Ré♭",marc:"em 2",fc:["6/8"],ri:"tético",s:["pontuada","fermata"]},
{n:66,tom:"Sol",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:67,tom:"Ré♭",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata","ritornelo"]},
{n:68,tom:"Ré",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:69,tom:"Ré♭",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:70,tom:"Sol",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:71,tom:"Dó",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:72,tom:"Lá♭",met:"69-84",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:73,tom:"Dó",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:74,tom:"Ré",met:"72-88",fc:["4/4"],ri:"tético",s:["pontuada","fermata","ritornelo"]},
{n:75,tom:"Lá♭",met:"69-84",fc:["3/4"],ri:"tético",s:["pontuada","fermata"]},
{n:76,tom:"Dó",marc:"em 6",fc:["6/4"],ri:"tético",s:["pontuada","fermata"]},
{n:77,tom:"Si♭",marc:"em 2",met:"112-138",fc:["6/8"],ri:"tético",s:["pontuada"]},
{n:78,tom:"Sol",fc:["6/8"],ri:"tético",s:["pontuada"]},
{n:79,tom:"Mi♭",met:"60-80",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:80,tom:"Lá♭",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:81,tom:"Dó",met:"108-120",fc:["6/8"],ri:"anacrúsico",s:["pontuada"]},
{n:82,tom:"Lá♭",met:"54-72",fc:["2/4"],ri:"anacrúsico",s:["pontuada"]},
{n:83,tom:"Mi♭",marc:"em 6",met:"88-112",fc:["6/4"],ri:"anacrúsico",s:["pontuada"]},
{n:84,tom:"Mi♭",met:"69-84",fc:["4/4"],ri:"tético",s:["pontuada","fermata"]},
{n:85,tom:"Lá♭",met:"66-92",fc:["4/4"],ri:"tético"},
{n:86,tom:"Mi♭",marc:"em 6",met:"80-108",fc:["6/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:87,tom:"Mi♭",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:88,tom:"Sol",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:89,tom:"Si♭",met:"80-96",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:90,tom:"Lá♭",met:"63-76",fc:["3/4"],ri:"anacrúsico",s:["pontuada"]},
{n:91,tom:"Ré♭",marc:"em 6",met:"92-120",fc:["6/4"],ri:"tético",s:["pontuada","fermata"]},
{n:92,tom:"Mi♭",met:"69-84",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata","ritornelo"]},
{n:93,tom:"Si♭",met:"60-72",fc:["3/4"],ri:"anacrúsico",s:["pontuada"]},
{n:94,tom:"Dó",marc:"em 4",met:"56-76",fc:["4/4","3/4"],ri:"anacrúsico",s:["pontuada"]},
{n:95,tom:"Lá♭",marc:"em 4",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:96,tom:"Sol",ind:"Solene",fc:["3/4"],ri:"tético",s:["pontuada"]},
{n:97,tom:"Lá♭",met:"42-52",fc:["6/8"],ri:"tético",s:["pontuada","fermata","ritornelo"]},
{n:98,tom:"Lá♭",marc:"em 6",fc:["6/4"],ri:"tético",s:["pontuada","fermata"]},
{n:99,tom:"Sol",met:"63-84",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:100,tom:"Si♭",met:"60-80",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:101,tom:"Sol",met:"60-72",fc:["4/4"],ri:"anacrúsico",s:["fermata"]},
{n:102,tom:"Mi♭",marc:"em 2",fc:["6/8"],ri:"tético",s:["pontuada","fermata","ritornelo"]},
{n:103,tom:"Dó",marc:"em 2",met:"72-88",fc:["4/4"],ri:"tético",s:["pontuada","fermata"]},
{n:104,tom:"Fá",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:105,tom:"Si♭",marc:"em 4",met:"44-60",fc:["12/8"],ri:"tético",s:["pontuada","fermata","ritornelo"]},
{n:106,tom:"Ré",met:"58-72",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:107,tom:"Fá",marc:"em 2",fc:["6/8"],ri:"anacrúsico",s:["pontuada"]},
{n:108,tom:"Sol",met:"60-80",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:109,tom:"Si♭",met:"112-132",fc:["6/8"],ri:"tético",s:["pontuada"]},
{n:110,tom:"Mi♭",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata","tercina"]},
{n:111,tom:"Mi♭",met:"63-80",fc:["3/4"],ri:"anacrúsico",s:["pontuada"]},
{n:112,tom:"Mi♭",met:"112-138",fc:["6/8"],ri:"anacrúsico",s:["pontuada"]},
{n:113,tom:"Mi♭",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:114,tom:"Si♭",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:115,tom:"Sol",fc:["3/4"],ri:"tético",s:["pontuada","fermata"]},
{n:116,tom:"Dó",marc:"em 2",fc:["6/8"],ri:"tético",s:["pontuada"]},
{n:117,tom:"Lá♭",met:"132-152",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:118,tom:"Ré♭",fc:["6/8"],ri:"anacrúsico",s:["pontuada"]},
{n:119,tom:"Mi♭",met:"88-112",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:120,tom:"Mi♭",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:121,tom:"Mi♭",fc:["9/8"],ri:"anacrúsico",s:["pontuada"]},
{n:122,tom:"Lá♭",met:"66-84",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:123,tom:"Si♭",fc:["3/4"],ri:"tético",s:["pontuada"]},
{n:124,tom:"Sol",marc:"em 6",met:"80-96",fc:["6/4"],ri:"tético",s:["pontuada","fermata"]},
{n:125,tom:"Fá",marc:"em 6",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:126,tom:"Lá♭",met:"63-80",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:127,tom:"Ré",met:"63-80",fc:["4/4"],ri:"tético",s:["pontuada","fermata"]},
{n:128,tom:"Si♭",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:129,tom:"Si♭",met:"66-80",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:130,tom:"Dó",fc:["6/8"],ri:"tético",s:["pontuada"]},
{n:131,tom:"Sol",met:"63-80",fc:["4/4"],ri:"tético"},
{n:132,tom:"Si♭",marc:"em 2",met:"108-132",fc:["6/8"],ri:"tético",s:["pontuada"]},
{n:133,tom:"Fá",met:"88-112",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:134,tom:"Mi♭",met:"66-80",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:135,tom:"Fá",ind:"Majestoso",fc:["C"],ri:"tético",s:["pontuada"]},
{n:136,tom:"Ré",marc:"em 2",fc:["6/8"],ri:"tético",s:["pontuada","fermata"]},
{n:137,tom:"Sol",met:"112-138",fc:["6/8"],ri:"tético",s:["pontuada"]},
{n:138,tom:"Lá",marc:"em 6",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata","ritornelo"]},
{n:139,tom:"Sol",met:"60-76",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:140,tom:"Fá",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:141,tom:"Mi♭",marc:"em 6",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:142,tom:"Fá",marc:"em 6",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:143,tom:"Ré",met:"66-80",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:144,tom:"Mi♭",met:"66-80",fc:["3/4"],ri:"tético",s:["pontuada"]},
{n:145,tom:"Ré♭",marc:"em 2",fc:["6/8"],ri:"tético",s:["pontuada"]},
{n:146,tom:"Ré",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:147,tom:"Lá♭",marc:"em 6",met:"72-88",ind:"Com júbilo",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:148,tom:"Lá♭",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:149,tom:"Sol",fc:["4/4"],ri:"tético",s:["pontuada","fermata","ritornelo"]},
{n:150,tom:"Lá♭",met:"54-69",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:151,tom:"Lá♭",met:"66-84",fc:["4/4"],ri:"tético",s:["pontuada","fermata"]},
{n:152,tom:"Lá♭",met:"72-92",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:153,tom:"Si♭",fc:["C"],ri:"anacrúsico",s:["pontuada"]},
{n:154,tom:"Mi♭",marc:"em 6",met:"108-126",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:155,tom:"Dó",fc:["4/4"],ri:"tético",s:["pontuada","fermata"]},
{n:156,tom:"Mi♭",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:157,tom:"Lá♭",fc:["3/4"],ri:"anacrúsico",s:["pontuada","tercina"]},
{n:158,tom:"Dó",met:"60-72",fc:["2/4"],ri:"tético"},
{n:159,tom:"Sol",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:160,tom:"Mi♭",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:161,tom:"Lá♭",met:"69-84",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:162,tom:"Sol",marc:"em 3",fc:["9/8"],ri:"anacrúsico",s:["pontuada","fermata","ritornelo"]},
{n:163,tom:"Mi♭",met:"112-138",fc:["6/8"],ri:"tético",s:["pontuada"]},
{n:164,tom:"Mi♭",met:"72-88",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:165,tom:"Si♭",marc:"em 2",fc:["6/8"],ri:"tético",s:["pontuada"]},
{n:166,tom:"Sol",marc:"em 6",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:167,tom:"Mi♭",met:"72-88",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:168,tom:"Si♭",met:"69-80",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:169,tom:"Lá♭",marc:"em 2",met:"100-126",fc:["6/8"],ri:"tético",s:["pontuada"]},
{n:170,tom:"Dó",marc:"em 3",fc:["9/8"],ri:"anacrúsico",s:["pontuada"]},
{n:171,tom:"Lá♭",met:"56-76",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:172,tom:"Dó",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:173,tom:"Si♭",met:"66-84",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:174,tom:"Lá♭",met:"66-84",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:175,tom:"Dó",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:176,tom:"Mi♭",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:177,tom:"Mi♭",marc:"em 3",fc:["9/8"],ri:"tético",s:["pontuada"]},
{n:178,tom:"Si♭",fc:["3/4"],ri:"anacrúsico",s:["pontuada"]},
{n:179,tom:"Mi♭",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:180,tom:"Sol",met:"76-88",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:181,tom:"Mi♭",met:"66-80",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:182,tom:"Si♭",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata","tercina"]},
{n:183,tom:"Mi♭",marc:"em 2",fc:["6/8"],ri:"tético",s:["pontuada"]},
{n:184,tom:"Sol",ind:"Solene",fc:["3/4"],ri:"tético",s:["pontuada"]},
{n:185,tom:"Sol",fc:["4/4"],ri:"tético",s:["pontuada","fermata","ritornelo"]},
{n:186,tom:"Mi♭",fc:["3/4"],ri:"tético",s:["pontuada"]},
{n:187,tom:"Ré",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:188,tom:"Lá",met:"69-84",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:189,tom:"Mi♭",met:"69-84",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:190,tom:"Si♭",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:191,tom:"Lá♭",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:192,tom:"Lá♭",met:"108-126",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:193,tom:"Mi♭",marc:"em 3",met:"120-144",fc:["9/8"],ri:"anacrúsico",s:["pontuada"]},
{n:194,tom:"Ré♭",fc:["C"],ri:"anacrúsico",s:["pontuada"]},
{n:195,tom:"Lá♭",met:"69-88",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:196,tom:"Si♭",met:"88-112",fc:["6/4"],ri:"tético",s:["pontuada","fermata"]},
{n:197,tom:"Fá",marc:"em 6",met:"84-104",fc:["6/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:198,tom:"Ré",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:199,tom:"Sol",met:"88-120",fc:["6/4"],ri:"anacrúsico",s:["pontuada"]},
{n:200,tom:"Lá",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:201,tom:"Dó",fc:["4/4"],ri:"tético",s:["pontuada","fermata"]},
{n:202,tom:"Ré",marc:"em 6",fc:["6/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:203,tom:"Ré",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:204,tom:"Ré♭",met:"66-80",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:205,tom:"Lá♭",marc:"em 4",met:"42-56",fc:["12/8"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:206,tom:"Mi♭",marc:"em 2",met:"100-138",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:207,tom:"Sol",marc:"em 2",met:"69-92",fc:["4/4"],ri:"tético",s:["pontuada","fermata"]},
{n:208,tom:"Fá",fc:["C cortado"],ri:"tético",s:["pontuada"]},
{n:209,tom:"Sol",met:"72-84",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:210,tom:"Mi♭",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:211,tom:"Dó",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata","tercina"]},
{n:212,tom:"Mi♭",met:"72-88",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:213,tom:"Mi♭",fc:["6/8"],ri:"tético",s:["pontuada"]},
{n:214,tom:"Ré",met:"66-76",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata","ritornelo"]},
{n:215,tom:"Dó",marc:"em 4",met:"44-60",fc:["12/8"],ri:"anacrúsico",s:["pontuada","fermata","ritornelo"]},
{n:216,tom:"Ré♭",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:217,tom:"Ré♭",marc:"em 2",fc:["6/8"],ri:"tético",s:["pontuada","fermata"]},
{n:218,tom:"Lá♭",met:"60-76",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:219,tom:"Si♭",marc:"em 2",fc:["6/8"],ri:"tético",s:["pontuada"]},
{n:220,tom:"Dó",met:"56-76",fc:["4/4"],ri:"tético",s:["pontuada","fermata"]},
{n:221,tom:"Mi♭",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:222,tom:"Si♭",met:"69-84",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:223,tom:"Fá",marc:"em 2",fc:["6/8"],ri:"tético",s:["pontuada"]},
{n:224,tom:"Dó",marc:"em 2",fc:["2/2"],ri:"tético",s:["pontuada"]},
{n:225,tom:"Mi♭",met:"63-84",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:226,tom:"Ré",met:"69-76",fc:["4/4"],ri:"anacrúsico",s:["fermata","ritornelo"]},
{n:227,tom:"Sol",met:"56-76",fc:["3/4"],ri:"acéfalo",s:["pontuada","fermata"]},
{n:228,tom:"Sol",met:"63-80",fc:["3/4"],ri:"anacrúsico",s:["pontuada"]},
{n:229,tom:"Ré",met:"69-92",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:230,tom:"Sol",met:"69-84",ri:"anacrúsico",s:["pontuada"]},
{n:231,tom:"Sol",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:232,tom:"Sol",met:"60-84",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:233,tom:"Dó",met:"69-84",fc:["4/4"],ri:"anacrúsico",s:["pontuada","tercina"]},
{n:234,tom:"Ré",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:235,tom:"Fá",met:"84-104",fc:["4/4"],ri:"tético"},
{n:236,tom:"Mi♭",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:237,tom:"Mi♭",met:"100-126",fc:["6/4"],ri:"tético",s:["pontuada"]},
{n:238,tom:"Ré♭",fc:["9/8"],ri:"anacrúsico",s:["pontuada","fermata","ritornelo"]},
{n:239,tom:"Fá",met:"60-76",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:240,tom:"Lá♭",met:"112-132",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:241,tom:"Fá",met:"66-84",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:242,tom:"Lá",met:"63-76",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:243,tom:"Sol",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:244,tom:"Fá",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:245,tom:"Sol",fc:["3/4"],ri:"tético",s:["pontuada","fermata"]},
{n:246,tom:"Lá♭",met:"116-132",fc:["6/8"],ri:"anacrúsico",s:["pontuada"]},
{n:247,tom:"Lá♭",marc:"em 4",met:"100-132",fc:["6/8"],ri:"tético",s:["pontuada","fermata","ritornelo"]},
{n:248,tom:"Ré",marc:"em 3",fc:["9/8"],ri:"anacrúsico",s:["pontuada"]},
{n:249,tom:"Si♭",met:"66-84",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:250,tom:"Ré",met:"60-76",fc:["3/4"],ri:"anacrúsico",s:["fermata"]},
{n:251,tom:"Sol",fc:["4/4"],ri:"tético",s:["pontuada","fermata","ritornelo"]},
{n:252,tom:"Mi♭",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:253,tom:"Sol",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:254,tom:"Fá",met:"52-66",fc:["4/4"],ri:"tético",s:["pontuada","fermata"]},
{n:255,tom:"Si♭",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:256,tom:"Sol",met:"100-120",fc:["6/4"],ri:"tético",s:["pontuada","fermata"]},
{n:257,tom:"Fá",met:"116-144",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:258,tom:"Si♭",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:259,tom:"Sol",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:260,tom:"Mi♭",marc:"em 6",fc:["6/8"],ri:"tético",s:["pontuada"]},
{n:261,tom:"Fá",fc:["2/2"],ri:"tético",s:["pontuada","fermata"]},
{n:262,tom:"Ré",met:"66-80",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:263,tom:"Ré",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:264,tom:"Dó",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:265,tom:"Si♭",marc:"em 3",fc:["6/8"],ri:"tético",s:["pontuada"]},
{n:266,tom:"Si♭",fc:["2/4"],ri:"tético"},
{n:267,tom:"Si♭",fc:["4/4"],ri:"tético",s:["pontuada","tercina"]},
{n:268,tom:"Fá",fc:["6/8"],ri:"tético",s:["pontuada","fermata","ritornelo"]},
{n:269,tom:"Sol",fc:["9/8"],ri:"anacrúsico",s:["pontuada"]},
{n:270,tom:"Mi♭",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:271,tom:"Sol",ind:"Com veneração",fc:["3/4"],ri:"tético",s:["pontuada"]},
{n:272,tom:"Mi♭",marc:"em 2",fc:["6/8"],ri:"tético",s:["pontuada","fermata","ritornelo"]},
{n:273,tom:"Lá♭",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:274,tom:"Mi♭",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:275,tom:"Lá",met:"66-84",fc:["4/4"],ri:"anacrúsico",s:["pontuada","tercina"]},
{n:276,tom:"Mi♭",met:"58-72",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:277,tom:"Sol",marc:"em 2",met:"120-144",fc:["6/8"],ri:"tético",s:["pontuada"]},
{n:278,tom:"Sol",fc:["6/8"],ri:"tético",s:["pontuada"]},
{n:279,tom:"Lá♭",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:280,tom:"Mi♭",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:281,tom:"Fá",met:"88-100",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:282,tom:"Dó",fc:["6/4"],ri:"tético",s:["pontuada","fermata"]},
{n:283,tom:"Sol",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:284,tom:"Fá",met:"66-80",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:285,tom:"Lá",met:"66-84",fc:["4/4"],ri:"tético",s:["pontuada","fermata"]},
{n:286,tom:"Ré",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:287,tom:"Sol",marc:"em 3",fc:["9/8"],ri:"anacrúsico",s:["pontuada"]},
{n:288,tom:"Sol",marc:"em 6",met:"108-120",fc:["6/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:289,tom:"Mi",met:"63-84",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:290,tom:"Lá♭",met:"72-92",fc:["4/4"],ri:"tético",s:["pontuada","fermata"]},
{n:291,tom:"Sol",met:"76-92",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:292,tom:"Si♭",met:"63-88",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:293,tom:"Mi♭",fc:["9/4"],ri:"anacrúsico",s:["pontuada"]},
{n:294,tom:"Mi♭",marc:"em 6",fc:["6/4"],ri:"anacrúsico",s:["pontuada"]},
{n:295,tom:"Sol",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:296,tom:"Si♭",fc:["3/4","4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:297,tom:"Sol",met:"100-126",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:298,tom:"Mi♭",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata","ritornelo"]},
{n:299,tom:"Mi♭",ind:"Solene",fc:["4/4"],ri:"tético",s:["pontuada","fermata"]},
{n:300,tom:"Ré",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:301,tom:"Ré♭",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:302,tom:"Dó",fc:["3/4"],ri:"anacrúsico",s:["pontuada"]},
{n:303,tom:"Dó",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:304,tom:"Mi♭",fc:["3/4"],ri:"tético",s:["pontuada","tercina"]},
{n:305,tom:"Lá♭",marc:"em 4",met:"88-112",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:306,tom:"Sol",met:"92-116",fc:["6/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:307,tom:"Mi♭",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:308,tom:"Lá♭",marc:"em 6",fc:["6/8"],ri:"tético",s:["pontuada","fermata"]},
{n:309,tom:"Lá♭",fc:["4/4"],ri:"tético",s:["pontuada","fermata"]},
{n:310,tom:"Si♭",ind:"Solene",fc:["2/4"],ri:"tético",s:["fermata"]},
{n:311,tom:"Lá♭",met:"69-84",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:312,tom:"Ré",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:313,tom:"Dó",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:314,tom:"Mi♭",met:"84-100",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:315,tom:"Sol",met:"80-100",fc:["6/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:316,tom:"Si♭",marc:"em 2",met:"44-56",fc:["6/8"],ri:"tético",s:["pontuada","fermata","ritornelo"]},
{n:317,tom:"Lá♭",fc:["6/8"],ri:"tético",s:["pontuada","fermata"]},
{n:318,tom:"Si♭",met:"60-76",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:319,tom:"Sol",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:320,tom:"Si♭",met:"60-80",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata","tercina"]},
{n:321,tom:"Lá♭",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:322,tom:"Dó",marc:"em 4",fc:["6/4"],ri:"tético",s:["pontuada"]},
{n:323,tom:"Si♭",met:"63-80",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:324,tom:"Dó",met:"63-76",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:325,tom:"Sol",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:326,tom:"Fá",fc:["6/8"],ri:"anacrúsico",s:["pontuada"]},
{n:327,tom:"Sol",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:328,tom:"Si♭",met:"63-80",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:329,tom:"Sol",marc:"em 6",fc:["6/8"],ri:"tético",s:["pontuada"]},
{n:330,tom:"Lá♭",met:"66-88",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:331,tom:"Lá♭",met:"66-84",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata","ritornelo"]},
{n:332,tom:"Si♭",fc:["6/8"],ri:"tético",s:["pontuada","fermata"]},
{n:333,tom:"Dó",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:334,tom:"Sol",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:335,tom:"Mi♭",fc:["2/4"],ri:"tético",s:["pontuada","fermata"]},
{n:336,tom:"Ré",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:337,tom:"Si♭",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata","ritornelo"]},
{n:338,tom:"Si♭",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:339,tom:"Lá♭",marc:"em 2",met:"112-132",fc:["6/4"],ri:"tético",s:["pontuada","fermata"]},
{n:340,tom:"Ré♭",marc:"em 2",fc:["6/4"],ri:"tético",s:["pontuada"]},
{n:341,tom:"Ré",fc:["6/8"],ri:"anacrúsico",s:["fermata"]},
{n:342,tom:"Dó",marc:"em 9",met:"88-112",fc:["9/4","6/4"],ri:"anacrúsico",s:["pontuada"]},
{n:343,tom:"Dó",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:344,tom:"Lá♭",met:"96-126",fc:["6/4"],ri:"tético",s:["pontuada"]},
{n:345,tom:"Fá",met:"69-84",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:346,tom:"Lá♭",marc:"em 6",fc:["6/4","9/4"],ri:"tético",s:["pontuada","fermata"]},
{n:347,tom:"Lá♭",marc:"em 2",met:"116-138",fc:["6/8"],ri:"tético",s:["pontuada","fermata","ritornelo"]},
{n:348,tom:"Dó",fc:["3/4","4/4"],ri:"anacrúsico",s:["pontuada","fermata","tercina"]},
{n:349,tom:"Mi♭",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:350,tom:"Ré",fc:["3/4","4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:351,tom:"Dó",fc:["6/8"],ri:"anacrúsico",s:["pontuada"]},
{n:352,tom:"Sol",fc:["3/4","4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:353,tom:"Sol",met:"58-69",fc:["C cortado"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:354,tom:"Sol",met:"69-80",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:355,tom:"Mi♭",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:356,tom:"Ré",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata","tercina"]},
{n:357,tom:"Fá",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:358,tom:"Dó",fc:["C"],ri:"tético",s:["pontuada"]},
{n:359,tom:"Ré",fc:["3/4","4/4"],ri:"anacrúsico",s:["pontuada","tercina"]},
{n:360,tom:"Mi♭",met:"66-80",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:361,tom:"Ré♭",fc:["6/4"],ri:"tético",s:["pontuada","fermata"]},
{n:362,tom:"Lá♭",met:"112-152",fc:["9/8"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:363,tom:"Sol",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:364,tom:"Dó",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:365,tom:"Lá♭",met:"56-76",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:366,tom:"Fá",met:"69-88",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:367,tom:"Ré",ind:"Majestoso",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:368,tom:"Sol",met:"66-84",fc:["4/4","3/4"],ri:"tético",s:["pontuada","fermata"]},
{n:369,tom:"Mi♭",marc:"em 2",met:"120-138",fc:["6/8"],ri:"tético",s:["pontuada","fermata"]},
{n:370,tom:"Mi♭",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:371,tom:"Mi♭",met:"60-76",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:372,tom:"Dó",met:"88-120",fc:["6/4"],ri:"anacrúsico",s:["pontuada","fermata","ritornelo"]},
{n:373,tom:"Lá♭",met:"63-80",fc:["3/4"],ri:"tético",s:["pontuada"]},
{n:374,tom:"Mi♭",met:"56-76",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:375,tom:"Dó",fc:["2/2"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:376,tom:"Mi♭",met:"66-80",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:377,tom:"Lá♭",met:"54-72",fc:["2/4"],ri:"acéfalo",s:["pontuada","fermata"]},
{n:378,tom:"Si♭",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:379,tom:"Lá♭",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:380,tom:"Ré",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:381,tom:"Ré♭",marc:"em 6",fc:["6/8"],ri:"tético",s:["pontuada","fermata"]},
{n:382,tom:"Si♭",fc:["4/4"],ri:"tético",s:["pontuada","fermata"]},
{n:383,tom:"Fá",fc:["6/8"],ri:"tético",s:["pontuada"]},
{n:384,tom:"Ré",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:385,tom:"Ré",fc:["3/4"],ri:"tético",s:["pontuada","fermata"]},
{n:386,tom:"Dó",met:"69-84",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:387,tom:"Ré♭",fc:["4/4"],ri:"tético"},
{n:388,tom:"Dó",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:389,tom:"Si♭",fc:["6/8"],ri:"tético",s:["pontuada"]},
{n:390,tom:"Dó",ind:"Majestoso",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:391,tom:"Lá♭",met:"58-72",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:392,tom:"Lá♭",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:393,tom:"Si♭",fc:["6/8"],ri:"tético",s:["pontuada","fermata"]},
{n:394,tom:"Ré",met:"69-80",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:395,tom:"Mi♭",ind:"Majestoso",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:396,tom:"Si♭",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:397,tom:"Lá♭",met:"66-80",fc:["3/4"],ri:"tético",s:["pontuada"]},
{n:398,tom:"Si♭",met:"50-63",fc:["2/2"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:399,tom:"Fá",marc:"em 3",fc:["9/8"],ri:"anacrúsico",s:["pontuada"]},
{n:400,tom:"Mi♭",fc:["3/4"],ri:"anacrúsico",s:["fermata"]},
{n:401,tom:"Dó",fc:["3/4"],ri:"anacrúsico",s:["pontuada"]},
{n:402,tom:"Fá",met:"60-80",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:403,tom:"Dó",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:404,tom:"Lá♭",met:"60-80",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:405,tom:"Lá♭",met:"63-76",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:406,tom:"Sol",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:407,tom:"Sol",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:408,tom:"Lá♭",fc:["3/2"],ri:"anacrúsico",s:["pontuada"]},
{n:409,tom:"Sol",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:410,tom:"Sol",fc:["2/2"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:411,tom:"Mi♭",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:412,tom:"Fá",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:413,tom:"Fá",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:414,tom:"Ré",met:"54-69",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:415,tom:"Dó",met:"80-100",fc:["9/8","6/8"],ri:"tético",s:["pontuada"]},
{n:416,tom:"Mi♭",fc:["C"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:417,tom:"Ré",marc:"em 6",fc:["6/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:418,tom:"Ré",marc:"em 3",fc:["9/8"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:419,tom:"Sol",marc:"em 4",fc:["2/2"],ri:"tético",s:["pontuada","fermata"]},
{n:420,tom:"Sol",met:"50-66",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:421,tom:"Mi♭",marc:"em 6",fc:["6/8"],ri:"anacrúsico",s:["pontuada"]},
{n:422,tom:"Mi♭",marc:"em 6",fc:["6/8","4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:423,tom:"Lá♭",met:"63-76",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:424,tom:"Fá",met:"58-80",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:425,tom:"Ré♭",marc:"em 9",fc:["9/8"],ri:"anacrúsico",s:["pontuada"]},
{n:426,tom:"Mi♭",met:"44-60",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:427,tom:"Mi♭",marc:"em 9",fc:["C"],ri:"tético",s:["pontuada"]},
{n:428,tom:"Fá",met:"56-60",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:429,tom:"Mi",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:430,tom:"Fá",marc:"em 6",fc:["6/8"],ri:"tético",s:["pontuada"]},
{n:431,tom:"Dó",met:"63-88",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:432,tom:"Lá♭",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:433,tom:"Si♭",fc:["3/4","4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:434,tom:"Dó",met:"66-84",fc:["4/4"]},
{n:435,tom:"Mi♭",fc:["3/4"],ri:"anacrúsico",s:["pontuada"]},
{n:436,tom:"Ré",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:437,tom:"Sol",met:"60-80",fc:["4/4"],ri:"tético"},
{n:438,tom:"Mi♭",marc:"em 2",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:439,tom:"Si♭",fc:["C"],ri:"anacrúsico",s:["pontuada"]},
{n:440,tom:"Fá",met:"63-92",fc:["C"],ri:"tético",s:["pontuada"]},
{n:441,tom:"Ré",marc:"em 2",met:"52-69",fc:["C cortado"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:442,tom:"Lá♭",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:443,tom:"Si♭",fc:["4/4"],ri:"tético",s:["fermata"]},
{n:444,tom:"Ré",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:445,tom:"Si♭",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:446,tom:"Sol",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:447,tom:"Mi♭",met:"69-84",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:448,tom:"Si♭",marc:"em 6",fc:["6/8"],ri:"anacrúsico",s:["pontuada"]},
{n:449,tom:"Lá♭",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:450,tom:"Lá♭",met:"63-84",fc:["4/4"],ri:"tético",s:["pontuada","fermata"]},
{n:451,tom:"Si♭",marc:"em 6",met:"104-132",fc:["6/8"],ri:"tético",s:["pontuada","fermata"]},
{n:452,tom:"Lá♭",met:"63-80",fc:["4/4"],ri:"anacrúsico",s:["pontuada"]},
{n:453,tom:"Fá",fc:["6/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:454,tom:"Sol",met:"104-126",fc:["6/8"],ri:"tético",s:["pontuada"]},
{n:455,tom:"Ré♭",met:"63-84",fc:["4/4"],ri:"tético",s:["pontuada","fermata"]},
{n:456,tom:"Mi♭",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:457,tom:"Dó",marc:"em 2",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata","ritornelo"]},
{n:458,tom:"Mi♭",met:"56-76",fc:["2/4"],ri:"tético",s:["pontuada","fermata"]},
{n:459,tom:"Dó",marc:"em 4",fc:["12/8"],ri:"anacrúsico",s:["pontuada","fermata","ritornelo"]},
{n:460,tom:"Fá",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:461,tom:"Dó",met:"69-84",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:462,tom:"Mi♭",fc:["3/4","4/4"],ri:"anacrúsico",s:["pontuada","fermata","tercina"]},
{n:463,tom:"Lá♭",fc:["4/4"],ri:"tético",s:["pontuada","fermata"]},
{n:464,tom:"Mi♭",ind:"Solene",fc:["3/4"],ri:"anacrúsico",s:["fermata","tercina"]},
{n:465,tom:"Si♭",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata","tercina","ritornelo"]},
{n:466,tom:"Sol",met:"63-80",fc:["3/4"],ri:"anacrúsico",s:["pontuada"]},
{n:467,tom:"Mi♭",met:"63-80",fc:["2/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:468,tom:"Fá",met:"63-80",fc:["2/4"],ri:"tético",s:["fermata"]},
{n:469,tom:"Lá♭",met:"76-84",fc:["4/4"],ri:"anacrúsico",s:["pontuada","tercina"]},
{n:470,tom:"Ré",fc:["C"],ri:"tético",s:["pontuada","fermata"]},
{n:471,tom:"Dó",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:472,tom:"Dó",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:473,tom:"Mi♭",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:474,tom:"Si♭",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:475,tom:"Mi♭",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata","ritornelo"]},
{n:476,tom:"Si♭",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:477,tom:"Si♭",fc:["4/4"],ri:"tético",s:["pontuada"]},
{n:478,tom:"Mi♭",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"]},
{n:479,tom:"Si♭",fc:["3/4"],ri:"anacrúsico",s:["pontuada"]},
{n:480,tom:"Si♭",marc:"em 2",fc:["6/8"],ri:"tético",s:["pontuada","fermata"]}
];
