/* Tabela dos hinos, extraída do hinário pelo ferramentas/extrair-hinario.py.

   Do cabeçalho:
   n    número do hino
   tom  tonalidade impressa
   marc movimento de marcação impresso ("em 2", "em 6"...), quando aparece
   met  marcação de metrônomo (a faixa; o número entre parênteses que vem
        depois dela no hinário não entra). Até 24/09/2026 faltava em 267 hinos:
        as cabeças de nota do primeiro sistema caíam no meio dos números.
   mf   a figura do sinal de metrônomo: semínima, colcheia, mínima, semínima
        pontuada. É o que diz se "100-138" são colcheias ou semínimas por
        minuto; a regência precisa disso para contar os gestos. O 272 (6/8
        em 2) vem impresso com ♩ = 42–52; o Anderson confirmou que é a
        semínima pontuada (24/09/2026), e assim está aqui.
   Tonalidade: em sete hinos o cabeçalho do PDF revisado escreve um tom que
   não é o da armadura (106, 189, 214, 272, 298, 299, 301). Vale a armadura,
   que bate com a relação de hinos por tonalidade da apostila de escalas da
   CCB — ver TOM_PELA_ARMADURA no extrator. Em quatro (102, 115, 168, 413)
   cabeçalho e armadura concordam e a relação diz outro tom: o Anderson
   conferiu no hinário dele (3 bemóis, 1 sustenido, 2 bemóis, 1 bemol) —
   vale o nosso; o erro é da relação. As fórmulas de compasso batem com a
   relação nos 480 hinos.
   Em oito hinos a marcação não é desenho do compasso ("em 4" num 2/4, "em 3"
   num 6/8: 32, 33, 147, 247, 265, 322, 419, 427). É agrupamento de frase, e
   rege-se pela fórmula — decisão do Anderson. O campo fica como impresso.
   ind  indicação interpretativa

   Da partitura (lida em 24/09/2026 — ver o script):
   fc   fórmulas de compasso, na ordem em que aparecem. Mais de uma quando o
        hino muda de compasso. "C" é o C de 4/4; "C cortado", o de 2/2.
        Conferido contra todas as listas do GEM que dependem de compasso.
   ri   ritmo inicial: tético, anacrúsico ou acéfalo. É o dado menos certo da
        tabela — sai do selo de regência do Maestro e da largura do primeiro
        compasso, e os casos duvidosos foram olhados um a um. Conferir no
        hinário antes de usar em avaliação.
   s    sinais presentes: pontuada (nota pontuada), fermata, tercina, ritornelo.
   arc  arcada impressa sobre a primeira nota: "baixo" (⊓) ou "cima" (V). O
        hinário marca arcada em todos os hinos, mas só no começo e onde o arco
        precisa virar — por isso só a da primeira nota está aqui. Falta em
        22 hinos: em 21 a primeira nota não traz marca, e o 434 não foi lido.
   sis  número de sistemas (pautas duplas).
   ag   nota mais aguda da pauta de Sol — é do soprano. Com a armadura, sem
        os acidentes ocorrentes: "Mi♭5".
   gr   nota mais grave da pauta de Sol — é do contralto.

   Nenhum desses campos reproduz a partitura: é informação sobre o hino, da
   mesma natureza da tonalidade.

   São os 480 hinos. O 434 não estava no PDF de onde o resto saiu — o 433 e o
   435 estão lá em páginas seguidas — e foi lido à mão da página que o Anderson
   digitalizou: Dó maior (clave de Sol sem acidente na armadura), compasso 4/4,
   metrônomo 66-84, sem indicação interpretativa. A marcação fica vazia porque
   a página que ele mandou é a do hinário com letra, que não traz esse campo.
   Do 434 não há ritmo inicial nem sinais: a página não foi lida pelo script.

   O 230 não traz fórmula de compasso impressa no começo, e fica sem "fc".

   Os hinos avulsos do fim do hinário não entram: eles recomeçam a numeração
   do 1 e colidiriam com os primeiros hinos.

   As marcações dos hinos 457 e 459 são anotação do Anderson na linha do
   título, e não impressão do hinário. Ficam porque ele as conferiu. */
const HINOS = [
{n:1,tom:"Mi♭",met:"56-66",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:4,ag:"Mi♭5",gr:"Si♭3"},
{n:2,tom:"Mi♭",met:"60-80",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:4,ag:"Mi♭5",gr:"Si♭3"},
{n:3,tom:"Sol",met:"60-76",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:5,ag:"Mi5",gr:"Si3"},
{n:4,tom:"Lá♭",marc:"em 2",met:"112-138",mf:"semínima",fc:["6/4"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:4,ag:"Mi♭5",gr:"Lá♭3"},
{n:5,tom:"Lá♭",marc:"em 2",met:"112-144",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada"],arc:"baixo",sis:5,ag:"Mi♭5",gr:"Lá♭3"},
{n:6,tom:"Dó",met:"60-80",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata","ritornelo"],arc:"cima",sis:5,ag:"Mi5",gr:"Si3"},
{n:7,tom:"Mi♭",marc:"em 6",met:"80-100",mf:"semínima",fc:["6/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:5,ag:"Mi♭5",gr:"Si♭3"},
{n:8,tom:"Si♭",marc:"em 2",met:"112-138",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada"],arc:"baixo",sis:4,ag:"Ré5",gr:"Ré4"},
{n:9,tom:"Sol",met:"63-72",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:4,ag:"Ré5",gr:"Si3"},
{n:10,tom:"Si♭",met:"69-84",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:5,ag:"Mi♭5",gr:"Lá3"},
{n:11,tom:"Si♭",met:"72-84",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:5,ag:"Ré5",gr:"Si♭3"},
{n:12,tom:"Mi♭",met:"58-76",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata","tercina"],arc:"cima",sis:4,ag:"Mi♭5",gr:"Si♭3"},
{n:13,tom:"Lá♭",met:"72-88",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:5,ag:"Mi♭5",gr:"Lá♭3"},
{n:14,tom:"Fá",met:"112-144",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada"],arc:"baixo",sis:6,ag:"Ré5",gr:"Sol3"},
{n:15,tom:"Si♭",marc:"em 4",met:"108-132",mf:"colcheia",fc:["12/8"],ri:"tético",s:["pontuada"],arc:"baixo",sis:3,ag:"Ré5",gr:"Si♭3"},
{n:16,tom:"Sol",marc:"em 6",met:"100-120",mf:"semínima",fc:["6/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Mi5",gr:"Si3"},
{n:17,tom:"Sol",met:"60-76",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"baixo",sis:5,ag:"Mi5",gr:"Si3"},
{n:18,tom:"Sol",met:"76-92",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:8,ag:"Mi5",gr:"Si3"},
{n:19,tom:"Lá♭",met:"63-80",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:6,ag:"Mi♭5",gr:"Dó4"},
{n:20,tom:"Fá",met:"72-84",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"baixo",sis:4,ag:"Ré5",gr:"Dó4"},
{n:21,tom:"Mi♭",marc:"em 6",met:"116-138",mf:"colcheia",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata","ritornelo"],arc:"cima",sis:10,ag:"Mi♭5",gr:"Si♭3"},
{n:22,tom:"Lá",marc:"em 6",met:"104-132",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada"],arc:"baixo",sis:4,ag:"Ré5",gr:"Lá3"},
{n:23,tom:"Sol",marc:"em 6",met:"96-120",mf:"semínima",fc:["6/4"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:4,ag:"Mi5",gr:"Si3"},
{n:24,tom:"Sol",marc:"em 6",met:"88-100",mf:"semínima",fc:["6/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:5,ag:"Ré5",gr:"Sol3"},
{n:25,tom:"Sol",met:"54-72",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Mi5",gr:"Lá3"},
{n:26,tom:"Lá♭",met:"69-88",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:8,ag:"Mi♭5",gr:"Si♭3"},
{n:27,tom:"Mi♭",marc:"em 2",met:"116-144",mf:"colcheia",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"baixo",sis:4,ag:"Mi♭5",gr:"Dó4"},
{n:28,tom:"Dó",met:"69-80",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:5,ag:"Mi5",gr:"Si3"},
{n:29,tom:"Lá♭",met:"66-84",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:6,ag:"Mi♭5",gr:"Dó4"},
{n:30,tom:"Fá",marc:"em 6",met:"100-132",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:4,ag:"Ré5",gr:"Si♭3"},
{n:31,tom:"Ré",met:"60-76",mf:"mínima",fc:["2/2"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:6,ag:"Ré5",gr:"Lá3"},
{n:32,tom:"Lá♭",marc:"em 4",met:"52-72",mf:"semínima",fc:["2/4"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:3,ag:"Mi♭5",gr:"Si♭3"},
{n:33,tom:"Dó",marc:"em 4",met:"112-132",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:7,ag:"Mi5",gr:"Sol3"},
{n:34,tom:"Mi♭",met:"50-66",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:2,ag:"Mi♭5",gr:"Si♭3"},
{n:35,tom:"Mi♭",met:"108-120",mf:"colcheia",fc:["6/8"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:5,ag:"Mi♭5",gr:"Si♭3"},
{n:36,tom:"Sol",met:"84-100",mf:"semínima",fc:["6/4"],ri:"anacrúsico",s:["pontuada"],arc:"baixo",sis:5,ag:"Ré5",gr:"Si3"},
{n:37,tom:"Ré",met:"69-88",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:6,ag:"Mi5",gr:"Lá3"},
{n:38,tom:"Mi♭",met:"56-72",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:2,ag:"Mi♭5",gr:"Si♭3"},
{n:39,tom:"Fá",met:"60-72",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"baixo",sis:4,ag:"Ré5",gr:"Dó4"},
{n:40,tom:"Lá♭",met:"72-88",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:4,ag:"Mi♭5",gr:"Lá♭3"},
{n:41,tom:"Lá",marc:"em 3",met:"120-144",mf:"colcheia",fc:["9/8"],ri:"anacrúsico",s:["pontuada","fermata","ritornelo"],arc:"cima",sis:8,ag:"Mi5",gr:"Si3"},
{n:42,tom:"Fá",marc:"em 4",met:"50-60",mf:"semínima pontuada",fc:["12/8"],ri:"anacrúsico",s:["pontuada","fermata","ritornelo"],arc:"cima",sis:8,ag:"Fá5",gr:"Lá3"},
{n:43,tom:"Mi♭",met:"60-80",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:4,ag:"Mi♭5",gr:"Si♭3"},
{n:44,tom:"Fá",marc:"em 3",met:"112-144",mf:"colcheia",fc:["9/8"],ri:"anacrúsico",s:["pontuada"],arc:"baixo",sis:5,ag:"Ré5",gr:"Si♭3"},
{n:45,tom:"Dó",marc:"em 3",met:"96-120",mf:"semínima",fc:["9/4"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:4,ag:"Ré5",gr:"Lá3"},
{n:46,tom:"Lá♭",marc:"em 2",met:"92-126",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:4,ag:"Mi♭5",gr:"Dó4"},
{n:47,tom:"Fá",marc:"em 2",met:"120-152",mf:"colcheia",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata","ritornelo"],arc:"cima",sis:8,ag:"Ré5",gr:"Si♭3"},
{n:48,tom:"Mi♭",met:"60-76",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"baixo",sis:4,ag:"Mi♭5",gr:"Si♭3"},
{n:49,tom:"Fá",marc:"em 6",met:"108-132",mf:"semínima",fc:["6/4"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:4,ag:"Si♭4",gr:"Lá3"},
{n:50,tom:"Dó",marc:"em 2",met:"108-144",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada","fermata","ritornelo"],arc:"baixo",sis:8,ag:"Fá5",gr:"Sol3"},
{n:51,tom:"Si♭",marc:"em 4",met:"66-80",mf:"semínima",fc:["C"],ri:"tético",arc:"baixo",sis:6,ag:"Mi♭5",gr:"Si♭3"},
{n:52,tom:"Dó",met:"108-144",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:4,ag:"Mi5",gr:"Sol3"},
{n:53,tom:"Mi♭",marc:"em 4",met:"72-92",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:4,ag:"Mi♭5",gr:"Si♭3"},
{n:54,tom:"Fá",met:"66-80",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Ré5",gr:"Sol3"},
{n:55,tom:"Dó",marc:"em 2",met:"112-132",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:9,ag:"Mi5",gr:"Si3"},
{n:56,tom:"Mi♭",met:"70-84",mf:"semínima",fc:["C"],ri:"tético",s:["pontuada","fermata","ritornelo"],arc:"baixo",sis:8,ag:"Mi♭5",gr:"Si♭3"},
{n:57,tom:"Ré♭",met:"69-84",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:5,ag:"Mi♭5",gr:"Dó4"},
{n:58,tom:"Ré",met:"69-92",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:4,ag:"Mi5",gr:"Lá3"},
{n:59,tom:"Fá",met:"60-76",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:4,ag:"Ré5",gr:"Si♭3"},
{n:60,tom:"Fá",marc:"em 2",met:"116-132",mf:"colcheia",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:4,ag:"Ré5",gr:"Dó4"},
{n:61,tom:"Mi♭",marc:"em 3",met:"132-144",mf:"colcheia",fc:["9/8"],ri:"anacrúsico",s:["pontuada","fermata","ritornelo"],arc:"baixo",sis:5,ag:"Mi♭5",gr:"Si♭3"},
{n:62,tom:"Lá♭",met:"63-80",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:3,ag:"Mi♭5",gr:"Dó4"},
{n:63,tom:"Si♭",marc:"em 3",met:"46-56",mf:"semínima pontuada",fc:["9/8"],ri:"anacrúsico",s:["pontuada","fermata","ritornelo"],arc:"baixo",sis:7,ag:"Fá5",gr:"Si♭3"},
{n:64,tom:"Fá",met:"69-88",mf:"semínima",fc:["3/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:2,ag:"Ré5",gr:"Si♭3"},
{n:65,tom:"Ré♭",marc:"em 2",met:"42-54",mf:"semínima pontuada",fc:["6/8"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:6,ag:"Mi♭5",gr:"Lá♭3"},
{n:66,tom:"Sol",met:"60-72",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:4,ag:"Mi5",gr:"Si3"},
{n:67,tom:"Ré♭",met:"63-80",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata","ritornelo"],arc:"cima",sis:8,ag:"Mi♭5",gr:"Dó4"},
{n:68,tom:"Ré",met:"60-76",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:4,ag:"Ré5",gr:"Lá3"},
{n:69,tom:"Ré♭",met:"63-84",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:4,ag:"Ré♭5",gr:"Lá♭3"},
{n:70,tom:"Sol",met:"63-80",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Mi5",gr:"Lá3"},
{n:71,tom:"Dó",met:"60-80",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:5,ag:"Mi5",gr:"Si3"},
{n:72,tom:"Lá♭",met:"69-84",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:4,ag:"Mi♭5",gr:"Dó4"},
{n:73,tom:"Dó",met:"69-84",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:5,ag:"Mi5",gr:"Si3"},
{n:74,tom:"Ré",met:"72-88",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada","fermata","ritornelo"],arc:"baixo",sis:7,ag:"Ré5",gr:"Lá3"},
{n:75,tom:"Lá♭",met:"69-84",mf:"semínima",fc:["3/4"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:2,ag:"Ré♭5",gr:"Dó4"},
{n:76,tom:"Dó",marc:"em 6",met:"100-126",mf:"semínima",fc:["6/4"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:4,ag:"Ré5",gr:"Lá3"},
{n:77,tom:"Si♭",marc:"em 2",met:"112-138",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada"],arc:"baixo",sis:4,ag:"Ré5",gr:"Ré4"},
{n:78,tom:"Sol",met:"112-132",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada"],arc:"baixo",sis:5,ag:"Mi5",gr:"Lá3"},
{n:79,tom:"Mi♭",met:"60-80",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Mi♭5",gr:"Si♭3"},
{n:80,tom:"Lá♭",met:"60-80",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:4,ag:"Mi♭5",gr:"Si♭3"},
{n:81,tom:"Dó",met:"108-120",mf:"colcheia",fc:["6/8"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:4,ag:"Ré5",gr:"Dó4"},
{n:82,tom:"Lá♭",met:"54-72",mf:"semínima",fc:["2/4"],ri:"anacrúsico",s:["pontuada"],arc:"baixo",sis:5,ag:"Mi♭5",gr:"Lá♭3"},
{n:83,tom:"Mi♭",marc:"em 6",met:"88-112",mf:"semínima",fc:["6/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:4,ag:"Ré5",gr:"Si♭3"},
{n:84,tom:"Mi♭",met:"69-84",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:4,ag:"Mi♭5",gr:"Si♭3"},
{n:85,tom:"Lá♭",met:"66-92",mf:"semínima",fc:["4/4"],ri:"tético",arc:"baixo",sis:5,ag:"Dó5",gr:"Si♭3"},
{n:86,tom:"Mi♭",marc:"em 6",met:"80-108",mf:"semínima",fc:["6/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Mi♭5",gr:"Si♭3"},
{n:87,tom:"Mi♭",met:"66-80",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Mi♭5",gr:"Si♭3"},
{n:88,tom:"Sol",met:"66-80",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:6,ag:"Mi5",gr:"Si3"},
{n:89,tom:"Si♭",met:"80-96",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:3,ag:"Mi♭5",gr:"Si♭3"},
{n:90,tom:"Lá♭",met:"63-76",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada"],arc:"baixo",sis:4,ag:"Ré♭5",gr:"Dó4"},
{n:91,tom:"Ré♭",marc:"em 6",met:"92-120",mf:"semínima",fc:["6/4"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:5,ag:"Mi♭5",gr:"Lá♭3"},
{n:92,tom:"Mi♭",met:"69-84",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata","ritornelo"],arc:"cima",sis:6,ag:"Mi♭5",gr:"Lá♭3"},
{n:93,tom:"Si♭",met:"60-72",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:3,ag:"Ré5",gr:"Si♭3"},
{n:94,tom:"Dó",marc:"em 4",met:"56-76",mf:"semínima",fc:["4/4","3/4"],ri:"anacrúsico",s:["pontuada"],arc:"baixo",sis:8,ag:"Mi5",gr:"Sol3"},
{n:95,tom:"Lá♭",marc:"em 4",met:"63-84",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Mi♭5",gr:"Lá♭3"},
{n:96,tom:"Sol",met:"72-92",mf:"semínima",ind:"Solene",fc:["3/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:3,ag:"Mi5",gr:"Ré4"},
{n:97,tom:"Lá♭",met:"42-52",mf:"semínima pontuada",fc:["6/8"],ri:"tético",s:["pontuada","fermata","ritornelo"],arc:"baixo",sis:8,ag:"Mi♭5",gr:"Lá♭3"},
{n:98,tom:"Lá♭",marc:"em 6",met:"88-126",mf:"semínima",fc:["6/4"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:5,ag:"Mi♭5",gr:"Lá♭3"},
{n:99,tom:"Sol",met:"63-84",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:5,ag:"Mi5",gr:"Si3"},
{n:100,tom:"Si♭",met:"60-80",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"baixo",sis:6,ag:"Mi♭5",gr:"Lá3"},
{n:101,tom:"Sol",met:"60-72",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["fermata"],arc:"cima",sis:3,ag:"Dó5",gr:"Dó4"},
{n:102,tom:"Mi♭",marc:"em 2",met:"116-144",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada","fermata","ritornelo"],arc:"baixo",sis:8,ag:"Mi♭5",gr:"Si♭3"},
{n:103,tom:"Dó",marc:"em 2",met:"72-88",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:6,ag:"Mi5",gr:"Lá3"},
{n:104,tom:"Fá",met:"69-84",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:3,ag:"Ré5",gr:"Lá3"},
{n:105,tom:"Si♭",marc:"em 4",met:"44-60",mf:"semínima pontuada",fc:["12/8"],ri:"tético",s:["pontuada","fermata","ritornelo"],arc:"baixo",sis:7,ag:"Mi♭5",gr:"Lá3"},
{n:106,tom:"Sol",met:"58-72",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:2,ag:"Ré5",gr:"Si3"},
{n:107,tom:"Fá",marc:"em 2",met:"40-50",mf:"semínima pontuada",fc:["6/8"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:6,ag:"Fá5",gr:"Lá3"},
{n:108,tom:"Sol",met:"60-80",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"baixo",sis:3,ag:"Mi5",gr:"Dó4"},
{n:109,tom:"Si♭",met:"112-132",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada"],arc:"baixo",sis:4,ag:"Ré5",gr:"Dó4"},
{n:110,tom:"Mi♭",met:"69-84",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata","tercina"],arc:"cima",sis:5,ag:"Mi♭5",gr:"Si♭3"},
{n:111,tom:"Mi♭",met:"63-80",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:6,ag:"Mi♭5",gr:"Si♭3"},
{n:112,tom:"Mi♭",met:"112-138",mf:"colcheia",fc:["6/8"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:4,ag:"Mi♭5",gr:"Si♭3"},
{n:113,tom:"Mi♭",met:"66-80",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:4,ag:"Mi♭5",gr:"Si♭3"},
{n:114,tom:"Si♭",met:"66-80",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:5,ag:"Mi♭5",gr:"Ré4"},
{n:115,tom:"Sol",met:"88-112",mf:"semínima",fc:["3/4"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:5,ag:"Mi5",gr:"Si3"},
{n:116,tom:"Dó",marc:"em 2",met:"108-138",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada"],arc:"baixo",sis:4,ag:"Mi5",gr:"Si3"},
{n:117,tom:"Lá♭",met:"132-152",mf:"colcheia",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:8,ag:"Mi♭5",gr:"Lá♭3"},
{n:118,tom:"Ré♭",met:"100-120",mf:"colcheia",fc:["6/8"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:6,ag:"Mi♭5",gr:"Lá♭3"},
{n:119,tom:"Mi♭",met:"88-112",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:3,ag:"Mi♭5",gr:"Si♭3"},
{n:120,tom:"Mi♭",met:"76-92",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:5,ag:"Mi♭5",gr:"Lá♭3"},
{n:121,tom:"Mi♭",met:"120-144",mf:"colcheia",fc:["9/8"],ri:"anacrúsico",s:["pontuada"],arc:"baixo",sis:5,ag:"Mi♭5",gr:"Si♭3"},
{n:122,tom:"Lá♭",met:"66-84",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:7,ag:"Mi♭5",gr:"Dó4"},
{n:123,tom:"Si♭",met:"63-84",mf:"semínima",fc:["3/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:2,ag:"Mi♭5",gr:"Dó4"},
{n:124,tom:"Sol",marc:"em 6",met:"80-96",mf:"semínima",fc:["6/4"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:5,ag:"Mi5",gr:"Dó4"},
{n:125,tom:"Fá",marc:"em 6",met:"96-120",mf:"colcheia",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Ré5",gr:"Si♭3"},
{n:126,tom:"Lá♭",met:"63-80",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:5,ag:"Mi♭5",gr:"Si♭3"},
{n:127,tom:"Ré",met:"63-80",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:5,ag:"Mi5",gr:"Lá3"},
{n:128,tom:"Si♭",met:"108-132",mf:"colcheia",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Ré5",gr:"Si♭3"},
{n:129,tom:"Si♭",met:"66-80",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"baixo",sis:5,ag:"Fá5",gr:"Lá3"},
{n:130,tom:"Dó",met:"112-144",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada"],arc:"baixo",sis:5,ag:"Mi5",gr:"Sol3"},
{n:131,tom:"Sol",met:"63-80",mf:"semínima",fc:["4/4"],ri:"tético",arc:"baixo",sis:4,ag:"Ré5",gr:"Si3"},
{n:132,tom:"Si♭",marc:"em 2",met:"108-132",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada"],arc:"baixo",sis:4,ag:"Mi♭5",gr:"Lá3"},
{n:133,tom:"Fá",met:"88-112",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:4,ag:"Ré5",gr:"Lá3"},
{n:134,tom:"Mi♭",met:"66-80",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:5,ag:"Dó5",gr:"Si♭3"},
{n:135,tom:"Fá",met:"72-84",mf:"semínima",ind:"Majestoso",fc:["C"],ri:"tético",s:["pontuada"],arc:"baixo",sis:4,ag:"Ré5",gr:"Dó4"},
{n:136,tom:"Ré",marc:"em 2",met:"112-144",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:4,ag:"Mi5",gr:"Lá3"},
{n:137,tom:"Sol",met:"112-138",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada"],arc:"baixo",sis:4,ag:"Mi5",gr:"Si3"},
{n:138,tom:"Lá",marc:"em 6",met:"104-144",mf:"colcheia",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata","ritornelo"],arc:"cima",sis:8,ag:"Mi5",gr:"Si3"},
{n:139,tom:"Sol",met:"60-76",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"],sis:4,ag:"Mi5",gr:"Si3"},
{n:140,tom:"Fá",met:"66-84",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:5,ag:"Ré5",gr:"Dó4"},
{n:141,tom:"Mi♭",marc:"em 6",met:"100-120",mf:"colcheia",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Mi♭5",gr:"Si♭3"},
{n:142,tom:"Fá",marc:"em 6",met:"88-112",mf:"colcheia",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Mi5",gr:"Si♭3"},
{n:143,tom:"Ré",met:"66-80",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"baixo",sis:6,ag:"Ré5",gr:"Sol3"},
{n:144,tom:"Mi♭",met:"66-80",mf:"semínima",fc:["3/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:3,ag:"Mi♭5",gr:"Lá♭3"},
{n:145,tom:"Ré♭",marc:"em 2",met:"108-138",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada"],arc:"baixo",sis:6,ag:"Mi♭5",gr:"Lá♭3"},
{n:146,tom:"Ré",met:"60-76",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:3,ag:"Mi5",gr:"Lá3"},
{n:147,tom:"Lá♭",marc:"em 6",met:"72-88",mf:"semínima",ind:"Com júbilo",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:5,ag:"Mi♭5",gr:"Si♭3"},
{n:148,tom:"Lá♭",met:"56-72",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"baixo",sis:4,ag:"Mi♭5",gr:"Dó4"},
{n:149,tom:"Sol",met:"72-88",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada","fermata","ritornelo"],arc:"baixo",sis:6,ag:"Mi5",gr:"Si3"},
{n:150,tom:"Lá♭",met:"54-69",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"baixo",sis:2,ag:"Mi♭5",gr:"Dó4"},
{n:151,tom:"Lá♭",met:"66-84",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:4,ag:"Dó5",gr:"Si♭3"},
{n:152,tom:"Lá♭",met:"72-92",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:4,ag:"Mi♭5",gr:"Lá♭3"},
{n:153,tom:"Si♭",met:"60-80",mf:"semínima",fc:["C"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:4,ag:"Mi♭5",gr:"Ré4"},
{n:154,tom:"Mi♭",marc:"em 6",met:"108-126",mf:"colcheia",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Mi♭5",gr:"Si♭3"},
{n:155,tom:"Dó",met:"60-76",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:5,ag:"Dó5",gr:"Si3"},
{n:156,tom:"Mi♭",met:"63-88",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:5,ag:"Mi♭5",gr:"Si♭3"},
{n:157,tom:"Lá♭",met:"60-72",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","tercina"],arc:"cima",sis:5,ag:"Ré♭5",gr:"Lá♭3"},
{n:158,tom:"Dó",met:"60-72",mf:"semínima",fc:["2/4"],ri:"tético",arc:"baixo",sis:3,ag:"Mi5",gr:"Lá3"},
{n:159,tom:"Sol",met:"60-76",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:6,ag:"Mi5",gr:"Lá3"},
{n:160,tom:"Mi♭",met:"88-112",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:3,ag:"Dó5",gr:"Ré4"},
{n:161,tom:"Lá♭",met:"69-84",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:5,ag:"Mi♭5",gr:"Si♭3"},
{n:162,tom:"Sol",marc:"em 3",met:"40-48",mf:"semínima pontuada",fc:["9/8"],ri:"anacrúsico",s:["pontuada","fermata","ritornelo"],arc:"baixo",sis:5,ag:"Ré5",gr:"Si3"},
{n:163,tom:"Mi♭",met:"112-138",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada"],arc:"baixo",sis:5,ag:"Mi♭5",gr:"Lá♭3"},
{n:164,tom:"Mi♭",met:"72-88",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:4,ag:"Mi♭5",gr:"Si♭3"},
{n:165,tom:"Si♭",marc:"em 2",met:"112-144",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada"],arc:"baixo",sis:4,ag:"Ré5",gr:"Si♭3"},
{n:166,tom:"Sol",marc:"em 6",met:"96-126",mf:"colcheia",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Ré5",gr:"Ré4"},
{n:167,tom:"Mi♭",met:"72-88",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:5,ag:"Ré5",gr:"Si♭3"},
{n:168,tom:"Si♭",met:"69-80",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Mi♭5",gr:"Lá3"},
{n:169,tom:"Lá♭",marc:"em 2",met:"100-126",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada"],arc:"baixo",sis:4,ag:"Mi♭5",gr:"Lá♭3"},
{n:170,tom:"Dó",marc:"em 3",met:"112-144",mf:"colcheia",fc:["9/8"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:5,ag:"Mi5",gr:"Dó4"},
{n:171,tom:"Lá♭",met:"56-76",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"baixo",sis:6,ag:"Mi♭5",gr:"Lá♭3"},
{n:172,tom:"Dó",met:"54-63",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:2,ag:"Ré5",gr:"Si3"},
{n:173,tom:"Si♭",met:"66-84",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:5,ag:"Mi♭5",gr:"Lá3"},
{n:174,tom:"Lá♭",met:"66-84",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"baixo",sis:5,ag:"Mi♭5",gr:"Lá♭3"},
{n:175,tom:"Dó",met:"63-80",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:4,ag:"Mi5",gr:"Si3"},
{n:176,tom:"Mi♭",met:"63-76",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:5,ag:"Mi♭5",gr:"Si♭3"},
{n:177,tom:"Mi♭",marc:"em 3",met:"40-50",mf:"semínima pontuada",fc:["9/8"],ri:"tético",s:["pontuada"],arc:"baixo",sis:6,ag:"Mi♭5",gr:"Lá♭3"},
{n:178,tom:"Si♭",met:"60-76",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:4,ag:"Mi♭5",gr:"Dó4"},
{n:179,tom:"Mi♭",met:"69-84",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Mi♭5",gr:"Si♭3"},
{n:180,tom:"Sol",met:"76-88",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Mi5",gr:"Sol3"},
{n:181,tom:"Mi♭",met:"66-80",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"baixo",sis:6,ag:"Mi♭5",gr:"Si♭3"},
{n:182,tom:"Si♭",met:"56-66",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata","tercina"],arc:"cima",sis:3,ag:"Mi♭5",gr:"Ré4"},
{n:183,tom:"Mi♭",marc:"em 2",met:"112-138",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada"],arc:"baixo",sis:6,ag:"Mi♭5",gr:"Si♭3"},
{n:184,tom:"Sol",met:"60-76",mf:"semínima",ind:"Solene",fc:["3/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:3,ag:"Mi5",gr:"Si3"},
{n:185,tom:"Sol",met:"66-84",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada","fermata","ritornelo"],arc:"baixo",sis:5,ag:"Mi5",gr:"Si3"},
{n:186,tom:"Mi♭",met:"66-80",mf:"semínima",fc:["3/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:5,ag:"Mi♭5",gr:"Si♭3"},
{n:187,tom:"Ré",met:"66-80",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:8,ag:"Mi5",gr:"Ré4"},
{n:188,tom:"Lá",met:"69-84",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"baixo",sis:5,ag:"Mi5",gr:"Lá3"},
{n:189,tom:"Lá♭",met:"69-84",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:4,ag:"Mi♭5",gr:"Dó4"},
{n:190,tom:"Si♭",met:"66-84",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:6,ag:"Ré5",gr:"Dó4"},
{n:191,tom:"Lá♭",met:"100-126",mf:"colcheia",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:4,ag:"Fá5",gr:"Dó4"},
{n:192,tom:"Lá♭",met:"108-126",mf:"colcheia",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Ré♭5",gr:"Lá♭3"},
{n:193,tom:"Mi♭",marc:"em 3",met:"120-144",mf:"colcheia",fc:["9/8"],ri:"anacrúsico",s:["pontuada"],arc:"baixo",sis:5,ag:"Mi♭5",gr:"Si♭3"},
{n:194,tom:"Ré♭",met:"60-76",mf:"semínima",fc:["C"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:4,ag:"Dó5",gr:"Lá♭3"},
{n:195,tom:"Lá♭",met:"69-88",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:4,ag:"Mi♭5",gr:"Dó4"},
{n:196,tom:"Si♭",met:"88-112",mf:"semínima",fc:["6/4"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:5,ag:"Ré5",gr:"Lá3"},
{n:197,tom:"Fá",marc:"em 6",met:"84-104",mf:"semínima",fc:["6/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Ré5",gr:"Lá3"},
{n:198,tom:"Ré",met:"76-100",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"baixo",sis:6,ag:"Ré5",gr:"Lá3"},
{n:199,tom:"Sol",met:"88-120",mf:"semínima",fc:["6/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:4,ag:"Mi5",gr:"Si3"},
{n:200,tom:"Lá",met:"60-80",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"baixo",sis:6,ag:"Mi5",gr:"Lá3"},
{n:201,tom:"Dó",met:"60-80",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:4,ag:"Mi5",gr:"Sol3"},
{n:202,tom:"Ré",marc:"em 6",met:"112-132",mf:"semínima",fc:["6/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Mi5",gr:"Lá3"},
{n:203,tom:"Ré",met:"66-80",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:5,ag:"Mi5",gr:"Lá3"},
{n:204,tom:"Ré♭",met:"66-80",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"baixo",sis:5,ag:"Mi♭5",gr:"Lá♭3"},
{n:205,tom:"Lá♭",marc:"em 4",met:"42-56",mf:"semínima pontuada",fc:["12/8"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Mi♭5",gr:"Si♭3"},
{n:206,tom:"Mi♭",marc:"em 2",met:"100-138",mf:"colcheia",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Mi♭5",gr:"Lá♭3"},
{n:207,tom:"Sol",marc:"em 2",met:"69-92",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:4,ag:"Dó5",gr:"Si3"},
{n:208,tom:"Fá",met:"44-54",mf:"mínima",fc:["C cortado"],ri:"tético",s:["pontuada"],arc:"cima",sis:4,ag:"Ré5",gr:"Dó4"},
{n:209,tom:"Sol",met:"72-84",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:5,ag:"Ré5",gr:"Si3"},
{n:210,tom:"Mi♭",met:"63-80",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:4,ag:"Mi♭5",gr:"Si♭3"},
{n:211,tom:"Dó",met:"60-76",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata","tercina"],arc:"cima",sis:4,ag:"Mi5",gr:"Si3"},
{n:212,tom:"Mi♭",met:"72-88",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:5,ag:"Mi♭5",gr:"Sol3"},
{n:213,tom:"Mi♭",met:"104-132",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada"],arc:"baixo",sis:4,ag:"Mi♭5",gr:"Si♭3"},
{n:214,tom:"Sol",met:"66-76",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata","ritornelo"],arc:"baixo",sis:8,ag:"Ré5",gr:"Si3"},
{n:215,tom:"Dó",marc:"em 4",met:"44-60",mf:"semínima pontuada",fc:["12/8"],ri:"anacrúsico",s:["pontuada","fermata","ritornelo"],arc:"cima",sis:6,ag:"Mi5",gr:"Lá3"},
{n:216,tom:"Ré♭",met:"100-132",mf:"colcheia",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:4,ag:"Mi♭5",gr:"Lá♭3"},
{n:217,tom:"Ré♭",marc:"em 2",met:"112-144",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:4,ag:"Mi♭5",gr:"Lá♭3"},
{n:218,tom:"Lá♭",met:"60-76",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"baixo",sis:4,ag:"Mi♭5",gr:"Lá♭3"},
{n:219,tom:"Si♭",marc:"em 2",met:"40-50",mf:"semínima pontuada",fc:["6/8"],ri:"tético",s:["pontuada"],sis:9,ag:"Mi♭5",gr:"Si♭3"},
{n:220,tom:"Dó",met:"56-76",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:5,ag:"Mi5",gr:"Lá3"},
{n:221,tom:"Mi♭",met:"60-80",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:4,ag:"Mi♭5",gr:"Si♭3"},
{n:222,tom:"Si♭",met:"69-84",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Mi♭5",gr:"Lá3"},
{n:223,tom:"Fá",marc:"em 2",met:"104-132",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada"],arc:"baixo",sis:5,ag:"Mi5",gr:"Lá3"},
{n:224,tom:"Dó",marc:"em 2",met:"54-66",mf:"mínima",fc:["2/2"],ri:"tético",s:["pontuada"],arc:"baixo",sis:5,ag:"Mi5",gr:"Dó4"},
{n:225,tom:"Mi♭",met:"63-84",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:5,ag:"Fá5",gr:"Si♭3"},
{n:226,tom:"Ré",met:"69-76",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["fermata","ritornelo"],arc:"baixo",sis:8,ag:"Ré5",gr:"Lá3"},
{n:227,tom:"Sol",met:"56-76",mf:"semínima",fc:["3/4"],ri:"acéfalo",s:["pontuada","fermata"],arc:"baixo",sis:4,ag:"Ré5",gr:"Lá3"},
{n:228,tom:"Sol",met:"63-80",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada"],sis:4,ag:"Mi5",gr:"Si3"},
{n:229,tom:"Ré",met:"69-92",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:6,ag:"Mi5",gr:"Lá3"},
{n:230,tom:"Sol",met:"69-84",mf:"semínima",ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:3,ag:"Mi5",gr:"Si3"},
{n:231,tom:"Sol",met:"104-132",mf:"colcheia",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Mi5",gr:"Si3"},
{n:232,tom:"Sol",met:"60-84",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:4,ag:"Mi5",gr:"Ré4"},
{n:233,tom:"Dó",met:"69-84",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","tercina"],arc:"cima",sis:6,ag:"Mi5",gr:"Sol3"},
{n:234,tom:"Ré",met:"66-80",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:4,ag:"Ré5",gr:"Lá3"},
{n:235,tom:"Fá",met:"84-104",mf:"semínima",fc:["4/4"],ri:"tético",arc:"baixo",sis:4,ag:"Ré5",gr:"Si♭3"},
{n:236,tom:"Mi♭",met:"63-76",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:5,ag:"Mi♭5",gr:"Si♭3"},
{n:237,tom:"Mi♭",met:"100-126",mf:"semínima",fc:["6/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:5,ag:"Mi♭5",gr:"Lá♭3"},
{n:238,tom:"Ré♭",met:"108-132",mf:"colcheia",fc:["9/8"],ri:"anacrúsico",s:["pontuada","fermata","ritornelo"],arc:"baixo",sis:5,ag:"Ré♭5",gr:"Lá♭3"},
{n:239,tom:"Fá",met:"60-76",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Fá5",gr:"Lá3"},
{n:240,tom:"Lá♭",met:"112-132",mf:"colcheia",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Mi♭5",gr:"Lá♭3"},
{n:241,tom:"Fá",met:"66-84",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:6,ag:"Fá5",gr:"Lá3"},
{n:242,tom:"Lá",met:"63-76",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:3,ag:"Mi5",gr:"Si3"},
{n:243,tom:"Sol",met:"72-92",mf:"colcheia",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Mi5",gr:"Si3"},
{n:244,tom:"Fá",met:"66-84",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:4,ag:"Mi5",gr:"Dó4"},
{n:245,tom:"Sol",met:"63-84",mf:"semínima",fc:["3/4"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:5,ag:"Ré5",gr:"Si3"},
{n:246,tom:"Lá♭",met:"116-132",mf:"colcheia",fc:["6/8"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:5,ag:"Mi♭5",gr:"Dó4"},
{n:247,tom:"Lá♭",marc:"em 4",met:"100-132",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada","fermata","ritornelo"],arc:"baixo",sis:5,ag:"Ré♭5",gr:"Lá♭3"},
{n:248,tom:"Ré",marc:"em 3",met:"112-138",mf:"colcheia",fc:["9/8"],ri:"anacrúsico",s:["pontuada"],arc:"baixo",sis:5,ag:"Mi5",gr:"Lá3"},
{n:249,tom:"Si♭",met:"66-84",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"baixo",sis:5,ag:"Ré5",gr:"Si♭3"},
{n:250,tom:"Ré",met:"60-76",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["fermata"],sis:5,ag:"Mi5",gr:"Lá3"},
{n:251,tom:"Sol",met:"72-92",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada","fermata","ritornelo"],arc:"baixo",sis:6,ag:"Mi5",gr:"Ré4"},
{n:252,tom:"Mi♭",met:"80-100",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:3,ag:"Mi♭5",gr:"Lá♭3"},
{n:253,tom:"Sol",met:"72-84",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"baixo",sis:7,ag:"Mi5",gr:"Sol3"},
{n:254,tom:"Fá",met:"52-66",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:2,ag:"Ré5",gr:"Dó4"},
{n:255,tom:"Si♭",met:"60-80",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:6,ag:"Ré5",gr:"Si♭3"},
{n:256,tom:"Sol",met:"100-120",mf:"semínima",fc:["6/4"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:3,ag:"Ré5",gr:"Si3"},
{n:257,tom:"Fá",met:"116-144",mf:"colcheia",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:7,ag:"Ré5",gr:"Lá3"},
{n:258,tom:"Si♭",met:"63-80",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:2,ag:"Mi♭5",gr:"Dó4"},
{n:259,tom:"Sol",met:"72-92",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:6,ag:"Mi5",gr:"Si3"},
{n:260,tom:"Mi♭",marc:"em 6",met:"108-126",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada"],arc:"baixo",sis:3,ag:"Fá5",gr:"Si♭3"},
{n:261,tom:"Fá",met:"50-66",mf:"mínima",fc:["2/2"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:6,ag:"Mi5",gr:"Lá3"},
{n:262,tom:"Ré",met:"66-80",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:3,ag:"Mi5",gr:"Lá3"},
{n:263,tom:"Ré",met:"72-84",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:5,ag:"Ré5",gr:"Dó♯4"},
{n:264,tom:"Dó",met:"66-80",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:4,ag:"Mi5",gr:"Dó4"},
{n:265,tom:"Si♭",marc:"em 3",met:"120-144",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada"],arc:"baixo",sis:6,ag:"Fá5",gr:"Lá3"},
{n:266,tom:"Si♭",met:"54-69",mf:"semínima",fc:["2/4"],ri:"tético",arc:"baixo",sis:3,ag:"Mi♭5",gr:"Dó4"},
{n:267,tom:"Si♭",met:"80-92",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada","tercina"],arc:"baixo",sis:8,ag:"Fá5",gr:"Lá3"},
{n:268,tom:"Fá",met:"126-152",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada","fermata","ritornelo"],arc:"baixo",sis:6,ag:"Fá5",gr:"Dó4"},
{n:269,tom:"Sol",met:"104-132",mf:"colcheia",fc:["9/8"],ri:"anacrúsico",s:["pontuada"],arc:"baixo",sis:3,ag:"Ré5",gr:"Dó4"},
{n:270,tom:"Mi♭",met:"69-92",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],sis:7,ag:"Mi♭5",gr:"Si♭3"},
{n:271,tom:"Sol",met:"80-96",mf:"semínima",ind:"Com veneração",fc:["3/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:2,ag:"Ré5",gr:"Si3"},
{n:272,tom:"Si♭",marc:"em 2",met:"42-52",mf:"semínima pontuada",fc:["6/8"],ri:"tético",s:["pontuada","fermata","ritornelo"],arc:"baixo",sis:8,ag:"Ré5",gr:"Si♭3"},
{n:273,tom:"Lá♭",met:"72-88",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],sis:5,ag:"Mi♭5",gr:"Dó4"},
{n:274,tom:"Mi♭",met:"56-66",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:4,ag:"Dó5",gr:"Si♭3"},
{n:275,tom:"Lá",met:"66-84",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","tercina"],arc:"cima",sis:7,ag:"Dó♯5",gr:"Si3"},
{n:276,tom:"Mi♭",met:"58-72",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:2,ag:"Mi♭5",gr:"Si♭3"},
{n:277,tom:"Sol",marc:"em 2",met:"120-144",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada"],arc:"baixo",sis:6,ag:"Mi5",gr:"Lá3"},
{n:278,tom:"Sol",met:"112-132",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada"],arc:"baixo",sis:3,ag:"Ré5",gr:"Si3"},
{n:279,tom:"Lá♭",met:"69-92",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:5,ag:"Mi♭5",gr:"Si♭3"},
{n:280,tom:"Mi♭",met:"116-144",mf:"colcheia",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Mi♭5",gr:"Si♭3"},
{n:281,tom:"Fá",met:"88-100",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:8,ag:"Mi5",gr:"Lá3"},
{n:282,tom:"Dó",met:"92-126",mf:"semínima",fc:["6/4"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:5,ag:"Fá5",gr:"Lá3"},
{n:283,tom:"Sol",met:"63-84",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Mi5",gr:"Si3"},
{n:284,tom:"Fá",met:"66-80",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:4,ag:"Ré5",gr:"Si♭3"},
{n:285,tom:"Lá",met:"66-84",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada","fermata"],sis:5,ag:"Dó♯5",gr:"Lá3"},
{n:286,tom:"Ré",met:"63-76",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Ré5",gr:"Lá3"},
{n:287,tom:"Sol",marc:"em 3",met:"120-144",mf:"colcheia",fc:["9/8"],ri:"anacrúsico",s:["pontuada"],arc:"baixo",sis:5,ag:"Mi5",gr:"Si3"},
{n:288,tom:"Sol",marc:"em 6",met:"108-120",mf:"semínima",fc:["6/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"baixo",sis:4,ag:"Ré5",gr:"Si3"},
{n:289,tom:"Mi",met:"63-84",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Mi5",gr:"Si3"},
{n:290,tom:"Lá♭",met:"72-92",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:5,ag:"Mi♭5",gr:"Lá♭3"},
{n:291,tom:"Sol",met:"76-92",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Mi5",gr:"Dó4"},
{n:292,tom:"Si♭",met:"63-88",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"baixo",sis:6,ag:"Mi♭5",gr:"Lá3"},
{n:293,tom:"Mi♭",met:"92-126",mf:"semínima",fc:["9/4"],ri:"anacrúsico",s:["pontuada"],arc:"baixo",sis:3,ag:"Ré5",gr:"Si♭3"},
{n:294,tom:"Mi♭",marc:"em 6",met:"104-132",mf:"semínima",fc:["6/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:7,ag:"Fá5",gr:"Si♭3"},
{n:295,tom:"Sol",met:"54-69",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:2,ag:"Ré5",gr:"Si3"},
{n:296,tom:"Si♭",met:"63-84",mf:"semínima",fc:["3/4","4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:6,ag:"Fá5",gr:"Si♭3"},
{n:297,tom:"Sol",met:"100-126",mf:"colcheia",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:4,ag:"Mi5",gr:"Si3"},
{n:298,tom:"Si♭",met:"69-88",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata","ritornelo"],arc:"cima",sis:6,ag:"Fá5",gr:"Lá3"},
{n:299,tom:"Si♭",met:"66-80",mf:"semínima",ind:"Solene",fc:["4/4"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:4,ag:"Ré5",gr:"Si♭3"},
{n:300,tom:"Ré",met:"63-88",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:6,ag:"Mi5",gr:"Si3"},
{n:301,tom:"Mi♭",met:"66-88",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:4,ag:"Mi♭5",gr:"Si♭3"},
{n:302,tom:"Dó",met:"63-80",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:6,ag:"Mi5",gr:"Si3"},
{n:303,tom:"Dó",met:"60-80",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:4,ag:"Mi5",gr:"Si3"},
{n:304,tom:"Mi♭",met:"63-76",mf:"semínima",fc:["3/4"],ri:"tético",s:["pontuada","tercina"],arc:"baixo",sis:5,ag:"Mi♭5",gr:"Si♭3"},
{n:305,tom:"Lá♭",marc:"em 4",met:"88-112",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:5,ag:"Mi♭5",gr:"Dó4"},
{n:306,tom:"Sol",met:"92-116",mf:"semínima",fc:["6/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:8,ag:"Ré5",gr:"Lá3"},
{n:307,tom:"Mi♭",met:"72-84",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:6,ag:"Mi♭5",gr:"Si♭3"},
{n:308,tom:"Lá♭",marc:"em 6",met:"108-126",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:4,ag:"Mi♭5",gr:"Si♭3"},
{n:309,tom:"Lá♭",met:"63-80",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:6,ag:"Mi♭5",gr:"Lá♭3"},
{n:310,tom:"Si♭",met:"58-72",mf:"semínima",ind:"Solene",fc:["2/4"],ri:"tético",s:["fermata"],arc:"baixo",sis:3,ag:"Mi♭5",gr:"Ré4"},
{n:311,tom:"Lá♭",met:"69-84",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:6,ag:"Mi♭5",gr:"Dó4"},
{n:312,tom:"Ré",met:"80-104",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:3,ag:"Mi5",gr:"Lá3"},
{n:313,tom:"Dó",met:"112-132",mf:"colcheia",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:9,ag:"Fá5",gr:"Si3"},
{n:314,tom:"Mi♭",met:"84-100",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:4,ag:"Mi♭5",gr:"Si♭3"},
{n:315,tom:"Sol",met:"80-100",mf:"semínima",fc:["6/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Mi5",gr:"Si3"},
{n:316,tom:"Si♭",marc:"em 2",met:"44-56",mf:"semínima pontuada",fc:["6/8"],ri:"tético",s:["pontuada","fermata","ritornelo"],arc:"baixo",sis:6,ag:"Ré5",gr:"Si♭3"},
{n:317,tom:"Lá♭",met:"92-132",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:4,ag:"Mi♭5",gr:"Lá♭3"},
{n:318,tom:"Si♭",met:"60-76",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Mi♭5",gr:"Lá3"},
{n:319,tom:"Sol",met:"69-84",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Mi5",gr:"Dó4"},
{n:320,tom:"Si♭",met:"60-80",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata","tercina"],arc:"cima",sis:6,ag:"Mi♭5",gr:"Si♭3"},
{n:321,tom:"Lá♭",met:"58-69",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:3,ag:"Mi♭5",gr:"Si♭3"},
{n:322,tom:"Dó",marc:"em 4",met:"104-132",mf:"semínima",fc:["6/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:6,ag:"Fá5",gr:"Si3"},
{n:323,tom:"Si♭",met:"63-80",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:4,ag:"Mi♭5",gr:"Si♭3"},
{n:324,tom:"Dó",met:"63-76",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:8,ag:"Mi5",gr:"Si3"},
{n:325,tom:"Sol",met:"112-138",mf:"colcheia",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Mi5",gr:"Si3"},
{n:326,tom:"Fá",met:"100-120",mf:"colcheia",fc:["6/8"],ri:"anacrúsico",s:["pontuada"],arc:"baixo",sis:5,ag:"Ré5",gr:"Dó4"},
{n:327,tom:"Sol",met:"76-92",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:5,ag:"Ré5",gr:"Ré4"},
{n:328,tom:"Si♭",met:"63-80",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:5,ag:"Mi♭5",gr:"Lá3"},
{n:329,tom:"Sol",marc:"em 6",met:"96-138",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada"],arc:"baixo",sis:5,ag:"Mi5",gr:"Si3"},
{n:330,tom:"Lá♭",met:"66-88",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Fá5",gr:"Lá♭3"},
{n:331,tom:"Lá♭",met:"66-84",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata","ritornelo"],arc:"baixo",sis:6,ag:"Mi♭5",gr:"Dó4"},
{n:332,tom:"Si♭",met:"116-132",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:4,ag:"Mi♭5",gr:"Lá3"},
{n:333,tom:"Dó",met:"60-80",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"baixo",sis:5,ag:"Mi5",gr:"Si3"},
{n:334,tom:"Sol",met:"69-80",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],sis:5,ag:"Ré5",gr:"Sol3"},
{n:335,tom:"Mi♭",met:"60-80",mf:"semínima",fc:["2/4"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:6,ag:"Mi♭5",gr:"Si♭3"},
{n:336,tom:"Ré",met:"66-88",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:4,ag:"Mi5",gr:"Lá3"},
{n:337,tom:"Si♭",met:"68-84",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata","ritornelo"],arc:"cima",sis:9,ag:"Mi♭5",gr:"Si♭3"},
{n:338,tom:"Si♭",met:"66-88",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:4,ag:"Mi♭5",gr:"Si♭3"},
{n:339,tom:"Lá♭",marc:"em 2",met:"112-132",mf:"semínima",fc:["6/4"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:5,ag:"Mi♭5",gr:"Lá♭3"},
{n:340,tom:"Ré♭",marc:"em 2",met:"108-132",mf:"semínima",fc:["6/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:5,ag:"Mi♭5",gr:"Dó4"},
{n:341,tom:"Ré",met:"92-132",mf:"colcheia",fc:["6/8"],ri:"anacrúsico",s:["fermata"],arc:"cima",sis:4,ag:"Ré5",gr:"Lá3"},
{n:342,tom:"Dó",marc:"em 9",met:"88-112",mf:"semínima",fc:["9/4","6/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:8,ag:"Ré5",gr:"Sol3"},
{n:343,tom:"Dó",met:"72-88",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:5,ag:"Mi5",gr:"Si3"},
{n:344,tom:"Lá♭",met:"96-126",mf:"semínima",fc:["6/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:5,ag:"Mi♭5",gr:"Si♭3"},
{n:345,tom:"Fá",met:"69-84",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"baixo",sis:5,ag:"Ré5",gr:"Si♭3"},
{n:346,tom:"Lá♭",marc:"em 6",met:"96-116",mf:"semínima",fc:["6/4","9/4"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:5,ag:"Mi♭5",gr:"Si♭3"},
{n:347,tom:"Lá♭",marc:"em 2",met:"116-138",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada","fermata","ritornelo"],arc:"baixo",sis:8,ag:"Mi♭5",gr:"Lá♭3"},
{n:348,tom:"Dó",met:"63-76",mf:"semínima",fc:["3/4","4/4"],ri:"anacrúsico",s:["pontuada","fermata","tercina"],arc:"cima",sis:5,ag:"Fá5",gr:"Si3"},
{n:349,tom:"Mi♭",met:"63-80",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Mi♭5",gr:"Si♭3"},
{n:350,tom:"Ré",met:"76-92",mf:"semínima",fc:["3/4","4/4"],ri:"anacrúsico",s:["pontuada"],sis:7,ag:"Mi5",gr:"Lá3"},
{n:351,tom:"Dó",met:"100-116",mf:"colcheia",fc:["6/8"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:2,ag:"Mi5",gr:"Si3"},
{n:352,tom:"Sol",met:"66-80",mf:"semínima",fc:["3/4","4/4"],ri:"anacrúsico",s:["pontuada","fermata"],sis:5,ag:"Mi5",gr:"Si3"},
{n:353,tom:"Sol",met:"58-69",mf:"mínima",fc:["C cortado"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Mi5",gr:"Si3"},
{n:354,tom:"Sol",met:"69-80",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"],sis:5,ag:"Mi5",gr:"Ré4"},
{n:355,tom:"Mi♭",met:"60-80",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:5,ag:"Mi♭5",gr:"Si♭3"},
{n:356,tom:"Ré",met:"66-84",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata","tercina"],arc:"cima",sis:6,ag:"Mi5",gr:"Lá3"},
{n:357,tom:"Fá",met:"56-72",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:4,ag:"Mi5",gr:"Dó4"},
{n:358,tom:"Dó",met:"63-80",mf:"semínima",fc:["C"],ri:"tético",s:["pontuada"],sis:4,ag:"Ré5",gr:"Si3"},
{n:359,tom:"Ré",met:"56-76",mf:"semínima",fc:["3/4","4/4"],ri:"anacrúsico",s:["pontuada","tercina"],sis:5,ag:"Mi5",gr:"Dó♯4"},
{n:360,tom:"Mi♭",met:"66-80",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Mi♭5",gr:"Si♭3"},
{n:361,tom:"Ré♭",met:"108-126",mf:"semínima",fc:["6/4"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:5,ag:"Mi♭5",gr:"Lá♭3"},
{n:362,tom:"Lá♭",met:"112-152",mf:"colcheia",fc:["9/8"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"baixo",sis:7,ag:"Mi♭5",gr:"Si♭3"},
{n:363,tom:"Sol",met:"54-72",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"baixo",sis:2,ag:"Mi5",gr:"Si3"},
{n:364,tom:"Dó",met:"63-80",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:5,ag:"Fá5",gr:"Sol3"},
{n:365,tom:"Lá♭",met:"56-76",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:4,ag:"Ré♭5",gr:"Dó4"},
{n:366,tom:"Fá",met:"69-88",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"baixo",sis:5,ag:"Ré5",gr:"Lá3"},
{n:367,tom:"Ré",met:"60-80",mf:"semínima",ind:"Majestoso",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:4,ag:"Mi5",gr:"Lá3"},
{n:368,tom:"Sol",met:"66-84",mf:"semínima",fc:["4/4","3/4"],ri:"tético",s:["pontuada","fermata"],sis:5,ag:"Ré5",gr:"Si3"},
{n:369,tom:"Mi♭",marc:"em 2",met:"120-138",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:4,ag:"Mi♭5",gr:"Si♭3"},
{n:370,tom:"Mi♭",met:"69-88",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"baixo",sis:6,ag:"Mi♭5",gr:"Si♭3"},
{n:371,tom:"Mi♭",met:"60-76",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"baixo",sis:4,ag:"Mi♭5",gr:"Si♭3"},
{n:372,tom:"Dó",met:"88-120",mf:"semínima",fc:["6/4"],ri:"anacrúsico",s:["pontuada","fermata","ritornelo"],arc:"baixo",sis:7,ag:"Mi5",gr:"Lá3"},
{n:373,tom:"Lá♭",met:"63-80",mf:"semínima",fc:["3/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:2,ag:"Ré♭5",gr:"Lá♭3"},
{n:374,tom:"Mi♭",met:"56-76",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:4,ag:"Mi♭5",gr:"Si♭3"},
{n:375,tom:"Dó",met:"40-54",mf:"mínima",fc:["2/2"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:4,ag:"Ré5",gr:"Si3"},
{n:376,tom:"Mi♭",met:"66-80",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:5,ag:"Mi♭5",gr:"Si♭3"},
{n:377,tom:"Lá♭",met:"54-72",mf:"semínima",fc:["2/4"],ri:"acéfalo",s:["pontuada","fermata"],arc:"cima",sis:4,ag:"Mi♭5",gr:"Si♭3"},
{n:378,tom:"Si♭",met:"56-72",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:5,ag:"Mi♭5",gr:"Lá3"},
{n:379,tom:"Lá♭",met:"76-84",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Mi♭5",gr:"Dó4"},
{n:380,tom:"Ré",met:"66-80",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"baixo",sis:8,ag:"Mi5",gr:"Lá3"},
{n:381,tom:"Ré♭",marc:"em 6",met:"100-126",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:8,ag:"Mi♭5",gr:"Lá♭3"},
{n:382,tom:"Si♭",met:"72-84",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:6,ag:"Mi♭5",gr:"Si♭3"},
{n:383,tom:"Fá",met:"104-132",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada"],arc:"baixo",sis:4,ag:"Ré5",gr:"Si♭3"},
{n:384,tom:"Ré",met:"60-76",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"baixo",sis:6,ag:"Ré5",gr:"Lá3"},
{n:385,tom:"Ré",met:"66-88",mf:"semínima",fc:["3/4"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:3,ag:"Ré5",gr:"Dó♯4"},
{n:386,tom:"Dó",met:"69-84",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:5,ag:"Mi5",gr:"Si3"},
{n:387,tom:"Ré♭",met:"104-126",mf:"semínima",fc:["4/4"],ri:"tético",arc:"baixo",sis:4,ag:"Mi♭5",gr:"Lá♭3"},
{n:388,tom:"Dó",met:"63-84",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:5,ag:"Ré5",gr:"Si3"},
{n:389,tom:"Si♭",met:"100-138",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada"],arc:"baixo",sis:5,ag:"Ré5",gr:"Si♭3"},
{n:390,tom:"Dó",met:"60-76",mf:"semínima",ind:"Majestoso",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:6,ag:"Mi5",gr:"Dó4"},
{n:391,tom:"Lá♭",met:"58-72",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:4,ag:"Mi♭5",gr:"Si♭3"},
{n:392,tom:"Lá♭",met:"63-84",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:6,ag:"Mi♭5",gr:"Lá♭3"},
{n:393,tom:"Si♭",met:"108-126",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:4,ag:"Ré5",gr:"Si♭3"},
{n:394,tom:"Ré",met:"69-80",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:6,ag:"Ré5",gr:"Lá3"},
{n:395,tom:"Mi♭",met:"92-112",mf:"semínima",ind:"Majestoso",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:3,ag:"Mi♭5",gr:"Si♭3"},
{n:396,tom:"Si♭",met:"63-76",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"baixo",sis:6,ag:"Ré5",gr:"Lá3"},
{n:397,tom:"Lá♭",met:"66-80",mf:"semínima",fc:["3/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:3,ag:"Ré♭5",gr:"Si♭3"},
{n:398,tom:"Si♭",met:"50-63",mf:"semínima",fc:["2/2"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:10,ag:"Fá5",gr:"Lá3"},
{n:399,tom:"Fá",marc:"em 3",met:"120-144",mf:"colcheia",fc:["9/8"],ri:"anacrúsico",s:["pontuada"],arc:"baixo",sis:5,ag:"Ré5",gr:"Si♭3"},
{n:400,tom:"Mi♭",met:"56-76",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["fermata"],arc:"cima",sis:4,ag:"Mi♭5",gr:"Lá♭3"},
{n:401,tom:"Dó",met:"63-88",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:5,ag:"Mi5",gr:"Lá3"},
{n:402,tom:"Fá",met:"60-80",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:4,ag:"Ré5",gr:"Lá3"},
{n:403,tom:"Dó",met:"63-80",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:5,ag:"Mi5",gr:"Lá3"},
{n:404,tom:"Lá♭",met:"60-80",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:5,ag:"Mi♭5",gr:"Lá♭3"},
{n:405,tom:"Lá♭",met:"63-76",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"baixo",sis:6,ag:"Mi♭5",gr:"Lá♭3"},
{n:406,tom:"Sol",met:"72-84",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:4,ag:"Mi5",gr:"Si3"},
{n:407,tom:"Sol",met:"66-88",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:6,ag:"Mi5",gr:"Si3"},
{n:408,tom:"Lá♭",met:"46-54",mf:"mínima",fc:["3/2"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:4,ag:"Fá5",gr:"Lá♭3"},
{n:409,tom:"Sol",met:"60-80",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:6,ag:"Ré5",gr:"Lá3"},
{n:410,tom:"Sol",met:"40-60",mf:"mínima",fc:["2/2"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:4,ag:"Ré5",gr:"Si3"},
{n:411,tom:"Mi♭",met:"54-69",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Mi♭5",gr:"Si♭3"},
{n:412,tom:"Fá",met:"46-58",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"],sis:3,ag:"Ré5",gr:"Lá3"},
{n:413,tom:"Fá",met:"50-69",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:6,ag:"Fá5",gr:"Dó4"},
{n:414,tom:"Ré",met:"54-69",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:3,ag:"Ré5",gr:"Dó♯4"},
{n:415,tom:"Dó",met:"80-100",mf:"colcheia",fc:["9/8","6/8"],ri:"tético",s:["pontuada"],arc:"baixo",sis:6,ag:"Fá5",gr:"Sol3"},
{n:416,tom:"Mi♭",met:"52-63",mf:"semínima",fc:["C"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:2,ag:"Mi♭5",gr:"Si♭3"},
{n:417,tom:"Ré",marc:"em 6",met:"84-108",mf:"semínima",fc:["6/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"baixo",sis:5,ag:"Ré5",gr:"Lá3"},
{n:418,tom:"Ré",marc:"em 3",met:"112-138",mf:"colcheia",fc:["9/8"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"baixo",sis:5,ag:"Ré5",gr:"Lá3"},
{n:419,tom:"Sol",marc:"em 4",met:"69-88",mf:"semínima",fc:["2/2"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:4,ag:"Mi5",gr:"Dó4"},
{n:420,tom:"Sol",met:"50-66",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:5,ag:"Mi5",gr:"Lá3"},
{n:421,tom:"Mi♭",marc:"em 6",met:"80-112",mf:"colcheia",fc:["6/8"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:4,ag:"Dó5",gr:"Si♭3"},
{n:422,tom:"Mi♭",marc:"em 6",met:"80-100",mf:"colcheia",fc:["6/8","4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"baixo",sis:5,ag:"Dó5",gr:"Si♭3"},
{n:423,tom:"Lá♭",met:"63-76",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"baixo",sis:5,ag:"Ré♭5",gr:"Lá♭3"},
{n:424,tom:"Fá",met:"58-80",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"baixo",sis:5,ag:"Ré5",gr:"Lá3"},
{n:425,tom:"Ré♭",marc:"em 9",met:"108-126",mf:"colcheia",fc:["9/8"],ri:"anacrúsico",s:["pontuada"],sis:6,ag:"Mi♭5",gr:"Dó4"},
{n:426,tom:"Mi♭",met:"44-60",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"baixo",sis:4,ag:"Mi♭5",gr:"Si♭3"},
{n:427,tom:"Mi♭",marc:"em 9",met:"44-58",mf:"semínima",fc:["C"],ri:"tético",s:["pontuada"],arc:"baixo",sis:5,ag:"Mi♭5",gr:"Si♭3"},
{n:428,tom:"Fá",met:"56-60",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:4,ag:"Ré5",gr:"Lá3"},
{n:429,tom:"Mi",met:"50-60",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:4,ag:"Mi5",gr:"Si3"},
{n:430,tom:"Fá",marc:"em 6",met:"96-112",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada"],arc:"baixo",sis:5,ag:"Ré5",gr:"Sol3"},
{n:431,tom:"Dó",met:"63-88",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"baixo",sis:4,ag:"Mi5",gr:"Sol3"},
{n:432,tom:"Lá♭",met:"84-108",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:4,ag:"Mi♭5",gr:"Dó4"},
{n:433,tom:"Si♭",met:"63-84",mf:"semínima",fc:["3/4","4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Mi♭5",gr:"Lá3"},
{n:434,tom:"Dó",met:"66-84",fc:["4/4"]},
{n:435,tom:"Mi♭",met:"63-76",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:3,ag:"Mi♭5",gr:"Si♭3"},
{n:436,tom:"Ré",met:"69-88",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"baixo",sis:7,ag:"Ré5",gr:"Lá3"},
{n:437,tom:"Sol",met:"60-80",mf:"semínima",fc:["4/4"],ri:"tético",arc:"baixo",sis:3,ag:"Ré5",gr:"Si3"},
{n:438,tom:"Mi♭",marc:"em 2",met:"100-138",mf:"colcheia",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:4,ag:"Mi♭5",gr:"Si♭3"},
{n:439,tom:"Si♭",met:"66-92",mf:"semínima",fc:["C"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:5,ag:"Fá5",gr:"Si♭3"},
{n:440,tom:"Fá",met:"63-92",mf:"semínima",fc:["C"],ri:"tético",s:["pontuada"],arc:"baixo",sis:5,ag:"Mi5",gr:"Lá3"},
{n:441,tom:"Ré",marc:"em 2",met:"52-69",mf:"mínima",fc:["C cortado"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:4,ag:"Ré5",gr:"Dó♯4"},
{n:442,tom:"Lá♭",met:"63-84",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:5,ag:"Mi♭5",gr:"Dó4"},
{n:443,tom:"Si♭",met:"60-88",mf:"semínima",fc:["4/4"],ri:"tético",s:["fermata"],arc:"baixo",sis:4,ag:"Mi♭5",gr:"Lá3"},
{n:444,tom:"Ré",met:"63-80",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"baixo",sis:4,ag:"Mi5",gr:"Lá3"},
{n:445,tom:"Si♭",met:"72-92",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:5,ag:"Fá5",gr:"Lá3"},
{n:446,tom:"Sol",met:"66-84",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:8,ag:"Mi5",gr:"Sol3"},
{n:447,tom:"Mi♭",met:"69-84",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:4,ag:"Mi♭5",gr:"Si♭3"},
{n:448,tom:"Si♭",marc:"em 6",met:"92-126",mf:"colcheia",fc:["6/8"],ri:"anacrúsico",s:["pontuada"],arc:"baixo",sis:5,ag:"Mi♭5",gr:"Si♭3"},
{n:449,tom:"Lá♭",met:"66-92",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:5,ag:"Mi♭5",gr:"Dó4"},
{n:450,tom:"Lá♭",met:"63-84",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:4,ag:"Ré♭5",gr:"Dó4"},
{n:451,tom:"Si♭",marc:"em 6",met:"104-132",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:4,ag:"Ré5",gr:"Si♭3"},
{n:452,tom:"Lá♭",met:"63-80",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:5,ag:"Mi♭5",gr:"Dó4"},
{n:453,tom:"Fá",met:"88-116",mf:"semínima",fc:["6/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"baixo",sis:5,ag:"Fá5",gr:"Lá3"},
{n:454,tom:"Sol",met:"104-126",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada"],arc:"baixo",sis:3,ag:"Mi5",gr:"Si3"},
{n:455,tom:"Ré♭",met:"63-84",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:5,ag:"Mi♭5",gr:"Lá♭3"},
{n:456,tom:"Mi♭",met:"60-80",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"baixo",sis:4,ag:"Mi♭5",gr:"Si♭3"},
{n:457,tom:"Dó",marc:"em 2",met:"104-144",mf:"colcheia",fc:["6/8"],ri:"anacrúsico",s:["pontuada","fermata","ritornelo"],arc:"cima",sis:7,ag:"Mi5",gr:"Si3"},
{n:458,tom:"Mi♭",met:"56-76",mf:"semínima",fc:["2/4"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:3,ag:"Mi♭5",gr:"Si♭3"},
{n:459,tom:"Dó",marc:"em 4",met:"112-144",mf:"colcheia",fc:["12/8"],ri:"anacrúsico",s:["pontuada","fermata","ritornelo"],arc:"cima",sis:7,ag:"Fá5",gr:"Si3"},
{n:460,tom:"Fá",met:"69-88",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:3,ag:"Fá5",gr:"Si♭3"},
{n:461,tom:"Dó",met:"69-84",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],sis:4,ag:"Mi5",gr:"Si3"},
{n:462,tom:"Mi♭",met:"69-84",mf:"semínima",fc:["3/4","4/4"],ri:"anacrúsico",s:["pontuada","fermata","tercina"],arc:"cima",sis:5,ag:"Mi♭5",gr:"Si♭3"},
{n:463,tom:"Lá♭",met:"66-88",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:5,ag:"Mi♭5",gr:"Dó4"},
{n:464,tom:"Mi♭",met:"60-72",mf:"semínima",ind:"Solene",fc:["3/4"],ri:"anacrúsico",s:["fermata","tercina"],arc:"baixo",sis:4,ag:"Mi♭5",gr:"Si♭3"},
{n:465,tom:"Si♭",met:"63-80",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata","tercina","ritornelo"],arc:"cima",sis:7,ag:"Mi♭5",gr:"Si♭3"},
{n:466,tom:"Sol",met:"63-80",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:2,ag:"Mi5",gr:"Ré4"},
{n:467,tom:"Mi♭",met:"63-80",mf:"semínima",fc:["2/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:6,ag:"Mi♭5",gr:"Si♭3"},
{n:468,tom:"Fá",met:"63-80",mf:"semínima",fc:["2/4"],ri:"tético",s:["fermata"],arc:"baixo",sis:3,ag:"Ré5",gr:"Dó4"},
{n:469,tom:"Lá♭",met:"76-84",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","tercina"],arc:"cima",sis:5,ag:"Mi♭5",gr:"Lá♭3"},
{n:470,tom:"Ré",met:"69-92",mf:"semínima",fc:["C"],ri:"tético",s:["pontuada","fermata"],arc:"baixo",sis:5,ag:"Mi5",gr:"Dó♯4"},
{n:471,tom:"Dó",met:"58-76",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:4,ag:"Ré5",gr:"Dó4"},
{n:472,tom:"Dó",met:"63-80",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:5,ag:"Ré5",gr:"Sol3"},
{n:473,tom:"Mi♭",met:"66-84",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"baixo",sis:5,ag:"Mi♭5",gr:"Si♭3"},
{n:474,tom:"Si♭",met:"60-84",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:5,ag:"Mi♭5",gr:"Si♭3"},
{n:475,tom:"Mi♭",met:"60-84",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata","ritornelo"],arc:"cima",sis:6,ag:"Mi♭5",gr:"Si♭3"},
{n:476,tom:"Si♭",met:"63-80",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"cima",sis:3,ag:"Mi♭5",gr:"Si♭3"},
{n:477,tom:"Si♭",met:"63-84",mf:"semínima",fc:["4/4"],ri:"tético",s:["pontuada"],arc:"baixo",sis:5,ag:"Mi♭5",gr:"Si♭3"},
{n:478,tom:"Mi♭",met:"63-80",mf:"semínima",fc:["4/4"],ri:"anacrúsico",s:["pontuada","fermata"],arc:"baixo",sis:5,ag:"Mi♭5",gr:"Si♭3"},
{n:479,tom:"Si♭",met:"63-80",mf:"semínima",fc:["3/4"],ri:"anacrúsico",s:["pontuada"],arc:"cima",sis:4,ag:"Ré5",gr:"Si♭3"},
{n:480,tom:"Si♭",marc:"em 2",met:"108-138",mf:"colcheia",fc:["6/8"],ri:"tético",s:["pontuada","fermata"],sis:4,ag:"Mi♭5",gr:"Lá3"}
];
